### PR TITLE
Add the support of RTM branch to the CI

### PR DESCRIPTION
**Pull request by zhenlan**
@iamjasonp please suggest if we need to add anything else to support RTM branch in CI. I guess we need to merge to be able to test this?

### CODE REVIEW

**Comment by iamjasonp** [comment]
You're close :smile:
Add a similar change to L51 (getJobName) to include an "rtm" entry. After that, please use the magic phrase "@dotnet-bot test ci please" to test out the groovy script to make sure there are no errors. 

After merge, we'll need to monitor things closely until we see passes

**Comment by zhenlan** [comment]
Thanks @iamjasonp. Updated as you suggested.

@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
LGTM

Prior to merge, please make sure there are at least 27 WcfService endpoints on our test server host. 
After merge, I would recommend triggering a couple of the _rtm queues just as a double check. Thanks!

**Comment by iamjasonp** [comment]
I did spot check some of the new _rtm queues for configuration issues, no issues found - but sometimes you really just gotta run things to figure out if the changes are good :smile:

**Pull request merged**
