### PR TITLE
Upgrade dotnet CLI version

### PR DESCRIPTION
**Pull request by dagood**
The CLI version upgrade changes restore from using DNX to using xplat nuget.

Should be the same changes as https://github.com/dotnet/corefx/pull/6337. The dir.props "extra" removal is because it was already removed in corefx during internal build package restore changes.

/cc @roncain @ericstj @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
LGTM once CI completes.

**Comment by roncain** [comment]
I'm doing a trial buddy build of this in TFS now.  Stay tuned...

**Comment by roncain** [comment]
@dotnet-bot test outerloop please

**Comment by roncain** [comment]
@dotnet-bot test outerloop please

**Comment by roncain** [comment]
LGTM

Caveats: TFS is being fixed now, and I would like to do a full build with this PR in place before we merge.
OuterLoops pass for me but appear to fail in CI due to fatal exceptions in the Bridge.  We will need to investigate the CI failures independently.

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by iamjasonp** [comment]
The CI failures are caused by a Bridge not cleaning up correctly. I've manually cleaned it up and am retrying the outerloops

**Comment by iamjasonp** [comment]
I built locally. Changes LGTM pending @roncain's build on TFS

**Comment by roncain** [comment]
LGTM -- TFS build succeeded. Jason would you mind merging?

**Comment by iamjasonp** [comment]
Done - will monitor builds that occur this evening

**Pull request merged**
