### PR TITLE
Update code coverage tooling versions

### PR DESCRIPTION
**Pull request by iamjasonp**
Coverage reporting was failing - update versions of OpenCover and ReportGenerator to latest stable versions.

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please
@dotnet-bot test outerloop please

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop Linux Debug Build and Test

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop Linux Release Build and Test

**Comment by roncain** [comment]
LGTM.  The Linux failures look like an out-of-disk-space problem, but I don't know why the Code Coverage test failed.

**Comment by iamjasonp** [comment]
@roncain 

> but I don't know why the Code Coverage test failed.

eh? Code Coverage is a green checkmark for me for this build...

**Comment by roncain** [comment]
Probably my mistake or time-of-the-day problem.  LGTM to merge.  I buddy tested in OSS but not TFS.

**Comment by iamjasonp** [comment]
This matches what corefx has today, so we should be good.

**Pull request merged**
