### PR TITLE
Update buildtools in 1.0.0

### PR DESCRIPTION
**Pull request by wtgodbe**
For dotnet/buildtools#2144 - takes the buildtools change to fix the copyright string.

CC @weshaggard @eerhardt

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by wtgodbe** [comment]
@dotnet-bot test outerloop selfhost Windows_NT Release

**Comment by wtgodbe** [comment]
@dotnet-bot test OuterLoop Selfhost Windows_NT Release

**Comment by wtgodbe** [comment]
@dotnet-bot help

**Comment by wtgodbe** [comment]
@dotnet-bot test all outerloop selfhost

**Comment by wtgodbe** [comment]
@StephenBonikowsky the Selfhost tests are failing with:

>  The process cannot access the file 'D:\j\workspace\outerloop_sel---1be3ffb0\SelfHostedWcfServiceSetup.log' because it is being used by another process

Any idea what's going on here? This has happened three times in a row now.

**Comment by StephenBonikowsky** [comment]
We see this happen when re-running the tests multiple times on the same machine. Something in one of the previous failed runs is hanging on to the setup log file. If we can re-run these on a different Jenkins machine it should be fine.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop selfhost Windows_NT

**Pull request merged**
