### PR TITLE
Move reference packages down a directory level so nuget restore pick up older versions

### PR DESCRIPTION
**Pull request by mconnew**
Latest version of nuget doesn't traverse any more directories if it finds a project.json
file in a folder. This means src\System.ServiceModel.Http\ref\project.json was stopping
src\System.ServiceModel.Http\ref\3.9.0\project.json from being found.

### CODE REVIEW

**Comment by mconnew** [comment]
@ericstj Can you validate that this approach won't break other things?

**Comment by ericstj** [comment]
This will break packages and partial facade projects.

**Comment by mconnew** [comment]
Any suggestions for a different approach? Without this change, WCF doesn't even successfully build.

**Comment by ericstj** [comment]
Use an item group (**\project.json) to grab all the project.json's and pass each one to dnu in series instead of passing the root.  It'll be slow but it's a small change to limp along until we can make a better fix.

**Pull request closed without merging**
