### PR TITLE
Fix issues in init-tools when path to git repo contains spaces

### PR DESCRIPTION
**Pull request by joperezr**
cc: @StephenBonikowsky

related: dotnet/corefx#8002

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Thanks @joperezr !
LGTM

**Comment by joperezr** [comment]
@StephenBonikowsky np :smile:  Do you mind merging the PR though? looks like I don't have write access to WCF repo for some reason.

**Comment by StephenBonikowsky** [comment]
Will do.

**Comment by StephenBonikowsky** [comment]
@roncain or @iamjasonp would you mind merging this once the checks look good?

**Comment by iamjasonp** [comment]
LGTM2. Since there was a change to the build tools, I'm going to run CI one more time. Shouldn't affect anything, but you never know :)

**Comment by iamjasonp** [comment]
@dotnet-bot test this please

**Pull request merged**
