### PR TITLE
Fixes for test web services to be able to pusblish metadata

### PR DESCRIPTION
**Pull request by mlacouture**

### CODE REVIEW

**Comment by zhenlan** [comment]
@dotnet-bot test all outerloop please

**Comment by roncain** [comment]
It looks like these changes are causing these OuterLoop tests to fail now:

```
MessageInterceptorTests.CustomBinding_Message_Interceptor
MessageContractTests.MessageBody_Elements_CustomerElement_Value_Matches
MessageContractTests.MessageContract_IsWrapped_False
MessageContractTests.MessageContract_IsWrapped_True
MessageContractTests.MessageHeader_MustUnderstand_True
MessageContractTests.MessageBody_Elements_Ordered
MessageContractTests.MessageHeader_MustUnderstand_False
```

**Comment by roncain** [comment]
@mlacouture  -- when you get the chance, we need to make this PR pass OuterLoops before it can be merged.  This command is what we normally run to test OuterLoops on our local dev machines:
```
    build.cmd /p:WithCategories=OuterLoop
```

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by roncain** [comment]
@mlacouture -- I rebased this PR on top of latest master, and it still fails those same OuterLoop tests.
You should be able to verify with "build.cmd /p:WithCategories=OuterLoop".  Failures typically look like this:

```
         Starting:    Contract.Message.Tests
            MessageContractTests.MessageBody_Elements_CustomerElement_Value_Matches [FAIL]
               System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.Private.ServiceModel, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]] : Error in deserializing body of request message for operation 'MessageContractRequestReply'. OperationFormatter encountered an invalid Message body. Expected to find node type 'Element' with name 'RequestBankingDataWrapper' and namespace 'http://www.contoso.com'. Found node type 'Element' with name 'CustomWrapperName' and namespace 'http://www.contoso.com'
               Stack Trace:
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(1069,0): at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(948,0): at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(782,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(722,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(369,0): at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)
                  c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(141,0): at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)
                  --- End of stack trace from previous location where exception was thrown ---
                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                     at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)
                     at generatedProxy_2.MessageContractRequestReply(RequestBankingData )
                  c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Contract\Message\MessageContractTests.cs(94,0): at MessageContractTests.MessageBody_Elements_CustomerElement_Value_Matches()
  
```

**Comment by iamjasonp** [comment]
@mlacouture, is this PR still active and being developed? It's been 4 months, so just checking whether we should close the PR and open another one later, or whether you intend to re-use this branch for continuing work. Thanks!

**Comment by hongdai** [comment]
Close this one. I will have a new pull request that based on the latest code and incorporate the changes here.

**Pull request closed without merging**
