### PR TITLE
Feed cleanup

### PR DESCRIPTION
**Pull request by mmitche**
Switch away from blob feeds

### CODE REVIEW

**Comment by mconnew** [comment]
You broke the build!!!! There are some packages which can't be found now.

**Comment by mmitche** [comment]
> You broke the build!!!! There are some packages which can't be found now.

Yep, I'll be iterating on this.

**Comment by mmitche** [comment]
Pushed up the targeting packs to dotnet-eng

**Comment by mmitche** [comment]
@mconnew Looks like the failures are consistent with other PR failures now.

**Comment by StephenBonikowsky** [comment]
@mmitche Yes, we have a failure on our test service machine. Until that gets resolved these failures are expected.

**Comment by mmitche** [comment]
> @mmitche Yes, we have a failure on our test service machine. Until that gets resolved these failures are expected.

Should I merge this then, or wait?

**Comment by mconnew** [comment]
@mmitche, feel free to merge at your leisure.

**Pull request merged**
