### PR TITLE
Prevent HttpClient from setting a timer on internal cancellation token

### PR DESCRIPTION
**Pull request by mconnew**
As HttpClient has a timeout set, it creates a linked cancellation token and calls CancelAfter on that linked token. By setting the default timeout to Infinite, HttpClient skips the call to CancelAfter. We were getting about 5% CPU usage updating the global TimerQueue because of this.
Also fixed an issue where we weren't unregistering a callback on our cancelation token which would have caused an unnecessary no-op callback.

### CODE REVIEW

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by roncain** [comment]
I think a rebase is required to make the PR tests pass, though I can't explain why yet.
Question only: can you double check that we have a test that verifies a normal Http request times out properly?
LGTM, subject to getting a CI pass by rebasing and verifying we have test coverage of the timeout.

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by roncain** [comment]
@dotnet-bot test outerloop Ubuntu14.04 Release

**Comment by mconnew** [comment]
ExpectedExceptionTests.SendTimeout_For_Long_Running_Operation_Throws_TimeoutException tests the timeout.  
The Ubuntu failures are for NetHttp and certificates so aren't related.

**Comment by roncain** [comment]
LGTM

**Pull request merged**
