### PR TITLE
Merge infrastructure branch to master

### PR DESCRIPTION
**Pull request by roncain**
Merges the infrastructure branch back to master.

The first commit of this PR is a feature branch off the Infrastructure branch that has been rebased onto the current master.  It contains no other changes other than a couple manual merges that could not be merged automatically, notably Endpoints.cs.

### CODE REVIEW

**Comment by roncain** [comment]
Reviewers: this is step 1, just a rebasing Infrastructure on master.  I will follow it with commits to add [ActiveIssue] or [ConditionalFact] where appropriate to get it to run clean.  As it is, it reduces the number of test failures via the new infrastructure to 14 (from 25).

**Comment by hongdai** [comment]
LGTM.

**Comment by zhenlan** [comment]
The plan is we don't do a detailed review for this infrastructure->master merge. @hongdai's ACK should be sufficient.

@roncain in step 2, can you please create a new ActiveIssue to skip all remaining failures that will need time to investigate? The idea is to get a real clean run (zero failures) on master.

**Comment by roncain** [comment]
@hongdai and @zhenlan -- I have pushed up commit 2 to apply [ActiveIssue] and am waiting for CI to finish testing.  Running this against the new test infrastructure has zero failures because tests are either marked with [ActiveIssue] or being skipped due to [ConditionalFact].

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT Debug, test outerloop Windows_NT Release

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT Debug, test outerloop Windows_NT Release

**Comment by hongdai** [comment]
The outerLoop failed because PR sync call failed:
 WCF Test Service Pull Request sync script
11:36:51  
11:36:51   [sync-pr] Making call to 'http://wcfcoresrv2.cloudapp.net/PRService10/pr.ashx?pr=1041'
11:36:57 Exception calling "DownloadString" with "1" argument(s): "The remote server 
11:36:57 returned an error: (400) Bad Request."
11:36:57 At line:1 char:1

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT Debug, test outerloop Windows_NT Release

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT Debug, test outerloop Windows_NT Release

**Comment by zhenlan** [comment]
Add LGTM here explicitly.

**Comment by iamjasonp** [comment]
LGTM post merge

**Pull request merged**
