### PR TITLE
Enable self-host startup script to run as Local System conditionally

### PR DESCRIPTION
**Pull request by roncain**
Adds an environment variable that can be set to alter whether the
self-hosted WCF services starts under the user account (default)
or runs as Local System.

### CODE REVIEW

**Comment by roncain** [comment]
Reviewers: this PR is intended to enable at least manual testing of authentication in cross-machine scenarios.  By setting PSEXEC_PATH to my psexec.exe, I can get all the failures reported in #1108 to pass.

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by roncain** [comment]
Ping... any feedback?  This is needed for cross-machine authentication verification we are doing for RTM and UWP. Thanks.
/cc @zhenlan @iamjasonp @StephenBonikowsky @hongdai

**Comment by hongdai** [comment]
LGTM.

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by iamjasonp** [comment]
LGTM2.

**Pull request merged**
