### PR TITLE
Update the buildtools and xunit runner packages

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
@mconnew @joperezr

**Comment by tarekgh** [comment]
CC @zhenlan

**Comment by StephenBonikowsky** [comment]
Thanks @tarekgh 
LGTM

**Comment by StephenBonikowsky** [comment]
Waiting for last CI

**Comment by tarekgh** [comment]
Test OuterLoop CentOS7.1 Debug please

**Pull request merged**
