### PR TITLE
Eliminate closure allocations

### PR DESCRIPTION
**Pull request by Maxwe11**

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
LGTM

**Comment by roncain** [comment]
LGTM.  Thanks @Maxwe11 !  I also pulled this patch and verified all our OuterLoop tests passed.

**Comment by iamjasonp** [comment]
LGTM, waiting for @mconnew's review as it's his area of expertise.

**Comment by mconnew** [comment]
Nice catch!! Merged.

**Pull request merged**
