### PR TITLE
Update netci.groovy scripts

### PR DESCRIPTION
**Pull request by iamjasonp**
* Add a help job to wcf repo
* Add msbuild.log to archived outerloop jobs

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
For context - this brings us reasonably up to date with the corefx netci.groovy minus a few stylistic issues. The dev workflow changes mentioned in #1506 are not part of this change

**Comment by iamjasonp** [comment]
Going to merge this now so I have time to test this out... @StephenBonikowsky can you please ACK after the fact

**Comment by StephenBonikowsky** [comment]
That looks like a lot of the changes I saw, not necessarily related tot he changes to the Dev Workflow.

LGTM

**Comment by iamjasonp** [comment]
Correct - pretty much none of these changes will have to do with the dev workflow; those changes will probably have to go in at the same time the script update happens

**Pull request merged**
