### PR TITLE
Test CI only

### PR DESCRIPTION
**Pull request by iamjasonp**

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test this please

**Comment by iamjasonp** [comment]
@dotnet-bot test innerloop windows_nt

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop windows_nt

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop windows_nt

**Comment by zhenlan** [comment]
@dotnet-bot test outerloop windows_nt debug

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop windows_nt

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Windows_NT

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop windows_nt ubuntu14.04 osx

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop osx

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop osx, test outerloop ubuntu14.04, test outerloop windows_nt

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop CentOS Debug Build and Test test Innerloop CentOS Release Build and Test

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test test Innerloop CentOS7.1 Release Build and Test

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by iamjasonp** [comment]
@dotnet-bot test this please

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop Windows_NT, test outerloop Ubuntu14.04, test outerloop CentOS7.1, test outerloop OSX

**Comment by iamjasonp** [comment]
@dotnet-bot test this

**Comment by iamjasonp** [comment]
@dotnet-bot test all outerloop please

**Comment by iamjasonp** [comment]
@dotnet-bot test all outerloop please

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop selfhost Windows_NT

**Pull request closed without merging**
