### PR TITLE
Automate certificate install for OSX, other *nixes

### PR DESCRIPTION
**Pull request by iamjasonp**
Adds support to BridgeCertificateInstaller.sh to install root certificates on non-Ubuntu OSes

### CODE REVIEW

**Comment by zhenlan** [comment]
Nice! @iamjasonp, can you please move the script to `tools/scripts` folder and clean up the `Bridge` in naming etc.?

**Comment by roncain** [comment]
LGTM, subject to @Zhenlan 's comments to move to scripts and eliminate Bridge naming in this file. Nice to see these changes!
Question only: what steps are required before this script can be run? I typically needed to do a full outerloop run to get everything built before I could run the prior one. Not blocking for this PR.

**Comment by iamjasonp** [comment]
Yes, due to the changes in build.sh (cmd), we have to do a full outerloop build before this command can run. I can put those instructions into the script usage info if it makes sense

**Comment by iamjasonp** [comment]
As discussed f2f with @zhenlan, we will: 

- merge this change without the "bridge" name cleanup, and then, 
- take the cleanup as a separate PR, to prevent muddling of the changes

There are a good number of references to "Bridge" which I will clean up at the same time - this will include things like the projects, names, and the like which will require a bit more effort. 

I want to push this through to unblock anyone else who might be waiting :smile:

**Comment by iamjasonp** [comment]
#1102 tracks renaming the Bridge to... whatever 😅 . I suspect a naming war will ensue in the next PR

**Comment by roncain** [comment]
LGTM to push this through as-is and deal with #1102 separately.

**Comment by iamjasonp** [comment]
Merging - this has been tested with Ubuntu, OS X, CentOS

**Pull request merged**
