### PR TITLE
Fixing Issue75

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
The first commit is for adding the two project reference tokens to 'test.props' and updating .csproj files to use them. Unfortunately I missed a few .csproj files and had to update them in one of the subsequent commits.

The second commit is to move the big common code project into ...\System.Private.ServiceModel\tests\Common\src

The final commit is to move the unit tests that were under System.Private.ServiceModel\tests into a new "Unit" subdirectory below there.

Fixing this Issue led to the creation of the following two new issues...
- Create test directory for test common code. #139
- Compartmentalize Scenario and Unit common code. #140

### CODE REVIEW

**Comment by SajayAntony** [comment]
@StephenBonikowsky Do your commits have "Fixes #139 and #140" somewhere so that they auto resolve and link the commit with the PR?

**Comment by StephenBonikowsky** [comment]
I didn't mean that this PR fixed those other two Issues, just that in the process of getting this PR ready I created two new issues that need to be fixed after this PR.

**Comment by SajayAntony** [comment]
:shipit:

**Comment by roncain** [comment]
Before I merge, let me prepare the TFS mirrored location so that it agrees with these new locations.  This will avoid a build breakage when nightly test runs occur.

**Comment by iamjasonp** [comment]
LGTM, subject to you having thought about @roncain's comment: 

> An alternate place to put these is wcf.targets at the root. I already started putting the names of other commonly used folders there. Not required, just an alternative.

I'll let @roncain decide when it's safe to merge.

**Comment by roncain** [comment]
LGTM.  Doing merge now and simultaneously updating TFS

**Pull request merged**
