### PR TITLE
Enable CI tests for PRs in release/2.1.0

### PR DESCRIPTION
**Pull request by StephenBonikowsky**

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test ci please

**Comment by StephenBonikowsky** [comment]
Waiting on https://github.com/dotnet/dotnet-ci/pull/919

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test ci please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Comment by zhenlan** [comment]
I assume only 1 netci.groovy file is going to be used by CI, so should this change be made in master branch instead?

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Pull request merged**
