### PR TITLE
Re-organized the Scenario Tests.

### PR DESCRIPTION
**Pull request by shmao**
Re-organized all the scenario tests so that we can use them to cover the scenario where latest Net Native tools + last released stable packages are used.

Ref #1048.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
LGTM

**Comment by shmao** [comment]
@dotnet-bot test all outerloop please

**Comment by zhenlan** [comment]
Thanks @shmao. It's a bit surprise to me so many tests worked with 4.0.0 packages. If you confirm they do, this LGTM.

**Comment by shmao** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 please

**Comment by shmao** [comment]
@zhenlan I confirm that the tests I moved to *.4.0.0.cs files passed with the latest Net Native tools built by N branch, which was a combination of latest ILC + RTM packages.

**Comment by zhenlan** [comment]
Thanks for the confirmation @shmao!

**Pull request merged**
