### PR TITLE
Use correct OSX monikers

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by StephenBonikowsky** [comment]
The test failure on Outerloop Selfhosted Windows_NT Debug is known issue.
With the test ci job passing are we good to merge? Then we can reset the OSX runs on the other PRs.

**Comment by mmitche** [comment]
@StephenBonikowsky hAng on, veryifying https://ci.dot.net/job/dotnet_wcf/job/master/job/GenPRTest/job/osx10.12_debug/

**Comment by mmitche** [comment]
@StephenBonikowsky Looks good.

**Comment by StephenBonikowsky** [comment]
Awesome, thanks @mmitche !

**Pull request merged**
