### PR TITLE
resubmit: Allow caller to await on TimeoutHelper.CancelationToken

### PR DESCRIPTION
**Pull request by shhsu**
Fixed a build issue from https://github.com/dotnet/wcf/pull/427

### CODE REVIEW

**Comment by roncain** [comment]
Thanks @shhsu -- just 2 questions:
1. Is the only difference in this PR the RTSocketConnection edits?  Or are there others?
2. What tests were done to verify this builds and runs in TFS?

**Comment by shhsu** [comment]
Yes, I have tried building the native and coreclr csproj files prior to this PR
Both @roncain and I have also performed a more complete build and got no errors.
Merging

**Comment by zhenlan** [comment]
@shhsu thanks for this work.

I did not see any new tests in this PR. Are existing tests sufficient to cover this or can more specific tests (inner or outer loop) be added for this?

**Comment by shhsu** [comment]
Functionally there's nothing new. I have privately run some verification to make sure there's performance improvement.

I have also verified the logic in TimeoutTokenSource by just running the code elsewhere and see the log output.

**Comment by zhenlan** [comment]
Thanks @shhsu. Sounds good if existing tests have covered all the new code path.

**Comment by roncain** [comment]
@KKhurin -- this PR contains the performance improvements described by @mconnew.  It would be good to verify this with any existing perf and stress tests

**Pull request merged**
