### PR TITLE
Updating the version of the .NET Core SDK to stable released version.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@nkolev92 @zivkan hoping you guys can helps with this.

After updating our dependency to Arcade (which in turn uses newer versions of dotnet.exe and nuget.exe) we are getting this error (see the Windows checks)...
```
.dotnet/sdk/3.0.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets#L198
.dotnet/sdk/3.0.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5129: (NETCORE_ENGINEERING_TELEMETRY=Build) - At least one .props file was found in 'build/', but 'build/dotnet-svcutil.xmlserializer.props/dotnet-svcutil.xmlserializer.props' was not.
- At least one .targets file was found in 'build/', but 'build/dotnet-svcutil.xmlserializer.targets/dotnet-svcutil.xmlserializer.targets' was not.
```
NU5129 was added with https://github.com/NuGet/NuGet.Client/pull/2982 I reviewed the documentation and I don't see what we are doing wrong.

According to [the doc](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/Creating-a-Package.md#include-msbuild-props-and-targets-in-a-package) we should be fine having these two files in the root `\build` folder and I checked the `<package_id>` and can confirm that the naming convention is correct.

[dotnet-svcutil.xmlserializer.props](https://github.com/dotnet/wcf/blob/master/src/svcutilcore/files/GenerateNupkgProps.targets#L9)
[dotnet-svcutil.xmlserializer.targets](https://github.com/dotnet/wcf/blob/master/src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj#L87
)

Is there something we are missing here or is there a bug in the implementation of NU5129?

Thanks.

**Comment by nkolev92** [comment]
Hey @StephenBonikowsky 

The messages there seem a bit off. 
If you can file an issue with the repro steps at nuget/home that's be great. 

I'd imagine it's merely checking out a certain repo/commit hash and just running pack on a certain project.

**Comment by StephenBonikowsky** [comment]
Thanks @nkolev92 I'm opening an issue now and suppressing the warning for now in our repo.

**Comment by StephenBonikowsky** [comment]
Opened https://github.com/NuGet/Home/issues/8627

**Pull request merged**
