### PR TITLE
Fix reporting for ETW traces in testing

### LINKED ISSUE #1440: FormatException in string.Format(item.Message, item.Payload) when formatting WCF events
When we format WCF Event traces by using string.Format(item.Message, item.Payload) to a  EventWrittenEventArgs, we sometimes see a FormatException complaining the number of arguments in Message and number of parameters in Payload does not match even though they match under the debugger. We need to investigate if there is a product bug.

### PR DESCRIPTION
**Pull request by iamjasonp**
Fixes #1440

### CODE REVIEW

**Comment by iamjasonp** [comment]
@hongdai - could you take a look please?

**Comment by mconnew** [comment]
LGTM

**Comment by roncain** [comment]
LGTM

**Comment by hongdai** [comment]
Missed it. A late LGTM.

**Comment by iamjasonp** [comment]
Thank you! Merged

**Pull request merged**
