### PR TITLE
Update to latest package versions

### PR DESCRIPTION
**Pull request by roncain**
Updates to package versions 23931-00 and latest build tools.

### CODE REVIEW

**Comment by roncain** [comment]
This PR is confirmed to fix the issue with ActiveIssue on Linux, and I would like to merge it if acceptable. It also takes a fix applied to CoreFx last night in dir.props.

/cc @iamjasonp @StephenBonikowsky @zhenlan

**Comment by StephenBonikowsky** [comment]
LGTM

**Comment by zhenlan** [comment]
LGTM

With this, we are in sync with corefx repo for buildtools.

**Comment by roncain** [comment]
Will merge now and do TFS confirmation in parallel.

**Pull request merged**
