### PR TITLE
Update build scripts based on changes in corefx.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Including build tools version and dotnet CLI version.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Not tested on Linux or in TFS.

**Comment by iamjasonp** [comment]
LGTM

**Comment by iamjasonp** [comment]
... pending a run on TFS

**Comment by roncain** [comment]
LGTM but we cannot test on Linux until #925 is merged.  It might be worth waiting for that merge to succeed first so we don't alter the build scripts while it is being validated.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop please

**Comment by StephenBonikowsky** [comment]
@roncain could you merge this if everything looks good on Linux?

**Comment by roncain** [comment]
@stebon -- we will need to chmod clean.sh on Linux to be executable like the other scripts, otherwise you need sudo to run it.  And if you install build tools as superuser, build.sh fails because it cannot execute corerun.  I believe the only way to do this is to touch it in Linux and check it in *from* Linux.

**Comment by roncain** [comment]
Running ./build.sh, I get this on Linux:
```
Setting up directories for build
Restoring NuGet.exe...
Installing dotnet cli...
Restoring BuildTools version 1.0.25-prerelease-00206...
Initializing BuildTools...
/home/roncain/git/wcf/Tools/dotnetcli/bin/dotnet compile-csc @/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/obj/Debug/dnxcore50/dotnet-compile.rsp returned Exit Code 1
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/project.json(35,30): error NU1001: The dependency Microsoft.Composition >= 1.0.30 could not be resolved.
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/project.json(37,37): warning NU1012: Dependency conflict. Microsoft.Build 0.1.0-preview-00017 expected System.Diagnostics.Contracts >= 4.0.1-rc2-23712 but got 4.0.0
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/project.json(37,37): warning NU1012: Dependency conflict. Microsoft.NETCore.Console 1.0.0-rc2-23907 expected System.Diagnostics.Contracts >= 4.0.1-rc2-23907 but got 4.0.0
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Client/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Client.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Common/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Common.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.ContentModel/3.4.0-rtm-0764/lib/dnxcore50/NuGet.ContentModel.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Frameworks/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Frameworks.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Logging/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Logging.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Packaging/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Packaging.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Packaging.Core/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Packaging.Core.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Packaging.Core.Types/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Packaging.Core.Types.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Repositories/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Repositories.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.RuntimeModel/3.4.0-rtm-0764/lib/dnxcore50/NuGet.RuntimeModel.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/NuGet.Versioning/3.4.0-rtm-0764/lib/dnxcore50/NuGet.Versioning.dll' could not be found
/home/roncain/git/wcf/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00206/lib/tool-runtime/error CS0006: Metadata file '/home/roncain/.nuget/packages/System.Diagnostics.Contracts/4.0.0/ref/dotnet/System.Diagnostics.Contracts.dll' could not be found
chmod: cannot access ‘/home/roncain/git/wcf/Tools/corerun’: No such file or directory
cp: cannot stat ‘/home/roncain/git/wcf/Tools/corerun’: No such file or directory
mv: cannot stat ‘/home/roncain/git/wcf/Tools/Microsoft.CSharp.targets’: No such file or directory
Done initializing tools.
./build.sh: line 111: /home/roncain/git/wcf/Tools/corerun: No such file or directory

tail: cannot open ‘/home/roncain/git/wcf/msbuild.log’ for reading: No such file or directory
Build Exit Code = 127
```

It may be a side-effect of trying to run clean.sh under sudo.  Investigating...

**Comment by roncain** [comment]
clean.cmd says there were errors during the clean, but clean.log doesn't show them.  This is being tracked by https://github.com/dotnet/corefx/issues/6973 .  We might want to wait till they fix this, or at least resync when they do.  Otherwise anyone building clean into a build script will error out.

**Comment by roncain** [comment]
@stebon -- I didn't merge pending investigation of getting clean fixed in CoreFx and getting it chmod'ed in Linux

**Comment by StephenBonikowsky** [comment]
I ran "git update-index --chmod=+x clean.sh" which is supposed to set the file as an executable for Linux.
I also updated the file with what looks like a fix that was made to it in corefx after which I don't see the error that was being reported.

**Comment by roncain** [comment]
LGTM if it passes CI

**Pull request merged**
