### PR TITLE
Port of dotnet/corefx#25644

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Restoring buildtools failed with...
* NuGet.Configuration.NuGetConfigurationException: Failed to read NuGet.Config due to unauthorized access.
* This PR in CoreFx fixes the problem.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@MattGal thought this change from CoreFx might resolve the buildtools restore failure were are seeing in VSO.

`NuGet.Configuration.NuGetConfigurationException: Failed to read NuGet.Config due to unauthorized access. Path: 'C:\Users\dlab\AppData\Roaming\NuGet\NuGet.Config'. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\dlab\AppData\Roaming\NuGet\NuGet.Config' is denied.`

**Comment by MattGal** [comment]
Continues to think so, even :)

**Comment by MattGal** [comment]
@zhenlan 

Basically 1) I made C:\Users\dlab\AppData\Roaming\NuGet\NuGet.Config read-only because this is global for every build run by this user, and people kept breaking machines by writing it with new features that aren't in older nugets, and 2) When those flags are not set, the CLI will try to write to that file on first-run (which is not good IMO).  

I think newer versions have some workaround for this, but this is the simplest way to stop it from trying to write this file.

**Comment by zhenlan** [comment]
@MattGal Thanks for the details!

**Pull request merged**
