### PR TITLE
Adding default value for FilterToTestTFM property used in VSO runs.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Essentially a port of Karthik's CoreFx PR #10042

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Needed to unblock our VSO runs.
@MattGal

**Comment by StephenBonikowsky** [comment]
@roncain have you seen these errors recently?

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Comment by MattGal** [comment]
LGTM once CI passes.

**Comment by roncain** [comment]
LGTM. I saw errors that looked related to this today.

**Pull request merged**
