### PR TITLE
Modify netci.groovy to support selfhosted outerloop

### PR DESCRIPTION
**Pull request by iamjasonp**
PR #1083 adds support for testing outerloops against SelfHostedWcfService, so we need a similar mechanism to do so in CI as well

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by roncain** [comment]
LGTM.  Does this need to wait for #1083 before merging?

**Comment by iamjasonp** [comment]
It doesn't need to wait per se, but all builds will fail until #1083 is merged

**Comment by roncain** [comment]
I opened issue #1098 due to an intermittent problem I am experiencing on my dev box using the new build startup scripts in #1083.  Just be aware there is a nonzero chance of it happening on CI.

**Comment by zhenlan** [comment]
LGTM

**Comment by zhenlan** [comment]
@dotnet-bot plesae test OuterLoop Selfhost Windows_NT

**Comment by iamjasonp** [comment]
@zhenlan, the trigger won't work until we actually merge. So I'll do so now, and let those selfhost builds fail.

**Comment by zhenlan** [comment]
Yes, I realized that. The trigger is still executed by the old code. Thanks 😄.

Since #1083 is merged now, the build may not fail.

**Pull request merged**
