### PR TITLE
PR 1019 broke CertificateCleanup.csproj

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* This is a temporary workaround to get CI checks working again.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop please

**Comment by hongdai** [comment]
LGTM. Thanks for taking care of it, Stephen!

**Comment by iamjasonp** [comment]
Post-merge LGTM. @StephenBonikowsky is there an issue filed for finding the permanent solution, or is it part of the script sync?

**Comment by StephenBonikowsky** [comment]
No issue needed, @hongdai is on it.

**Pull request merged**
