### PR TITLE
Add command-line option "quiet" for svcutil.xmlserializer, and fail the run when customer trying to use the tool directly

### LINKED ISSUE #2884: Add warning by default in svcutil.xmlserializer
Output the warning by default when the customer try to run our tool directly. Add a parameter quiet to suppress this message when using it in the .csproj.

Refer #24054

### PR DESCRIPTION
**Pull request by yujayee**
Fixes #2884

### CODE REVIEW

**Comment by yujayee** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug please
@dotnet-bot test wcf-azure-pipeline please

**Comment by yujayee** [comment]
@mconnew @huanwu I've resolved the merge conflicts. Could you take a look if the changes look good? Thanks!

**Comment by r-pankevicius** [comment]
Please, could you explain more why "customer is trying to use the tool directly" is bad? I don't get this attitude.

**Comment by yujayee** [comment]
Svcutil.xmlserializer should be used by installing the dotnet-svcutil.xmlserializer nuget package. This pr is to show a warning message and fail the run when users try to run the dll directly.

**Comment by huanwu** [comment]
@r-pankevicius The direct usage of this tool won't work on dotnet core. That's why we send the warning message.

**Comment by yujayee** [comment]
@dotnet test all please

**Comment by yujayee** [comment]
@dotnet-bot test all please

**Comment by mconnew** [comment]
LGTM

**Comment by yujayee** [comment]
I remembered all tests were passed but then on one day some of them suddenly failed. I assume the test failure is not related to the code change. I'll try to rerun the tests.

**Comment by yujayee** [comment]
@dotnet-bot test OuterLoop CentOS7.1 Debug

**Comment by StephenBonikowsky** [comment]
@yujayee 
We moved the master branch onto the new Arcade infrastructure and the Jenkins tests have all been removed.
It's ok to go ahead and merge.

**Comment by yujayee** [comment]
Thanks @StephenBonikowsky I'll go ahead and merge it.

**Pull request merged**
