### PR TITLE
Modify digest authenticator to accept realm\\username username

### PR DESCRIPTION
**Pull request by mconnew**
Works around Issue #1332

### CODE REVIEW

**Comment by mconnew** [comment]
@dotnet-bot test outerloop CentOS7.1, test outerloop Ubuntu14.01

**Comment by mconnew** [comment]
@dotnet-bot test outerloop CentOS7.1
@dotnet-bot test outerloop Ubuntu14.01

**Comment by mconnew** [comment]
It looks like this is still failing all the time on CentOS so I won't merge this fix until I understand that issue. The Ubuntu failure is due to the intermittent streaming test failures.

**Comment by roncain** [comment]
LGTM, subject to getting CentOS passing.

**Comment by mconnew** [comment]
CentOS failure was caused by CI infrastructure issue, retrying.
@dotnet-bot test outerloop CentOS7.1

**Comment by mconnew** [comment]
Sigh, picked up the same bad node again. It's being deleted so time to try again!
@dotnet-bot test outerloop CentOS7.1

**Pull request merged**
