### PR TITLE
Update buildtools

### PR DESCRIPTION
**Pull request by roncain**

### CODE REVIEW

**Comment by roncain** [comment]
Please do *not* merge until I have verified this builds in TFS correctly.

**Comment by roncain** [comment]
Reviewers: any diff's you see originated from copying the equivalent files verbatim from CoreFx or hand merging to retain our customizations but take their latest touches.  Some are related to x-plat testing, which is what motivated this PR.

**Comment by roncain** [comment]
@iamjasonp @mconnew @hongdai @StephenBonikowsky -- I would appreciate it if anyone could buddy build this in TFS.  I am having trouble getting TFS to build period.  It would involve getting this PR and manually copying all the files into FxCore\WcfOpen, then building all of FxCore from scratch.  I need to get this merged to help Linux testing (and to stop generating .lock.json files every build).

**Comment by iamjasonp** [comment]
Incremental buddy build passed earlier today; I'm doing a full rebuild (`msbuild dirs.proj /t:rebuild`) now

**Comment by iamjasonp** [comment]
@roncain - full rebuild passed for me. Still would recommend a gated checkin into TFS

**Comment by roncain** [comment]
@iamjasonp -- thanks. Do you recommend this checkin also originate from TFS, or just test the shelveset against TFS and merge through GH?

**Comment by iamjasonp** [comment]
Hmm, we could just merge here and beg for forgiveness if something goes wrong :)

**Comment by iamjasonp** [comment]
This is being submitted via TFS as a gated check-in. Will close this PR once (if?) successful.

**Comment by iamjasonp** [comment]
TFS gated build turned out to have issues too, and we need this in asap. 
@roncain updated a bunch of stuff, which LGTM. Merging now.

**Pull request merged**
