### PR TITLE
Testing the new UAP CI Job.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot help

**Comment by iamjasonp** [comment]
(it's been a long time, so just saying hi :wave:)

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
@mconnew if you have a chance can you take a look at the Jenkins failure for the new UAP CI job...
https://ci.dot.net/job/dotnet_wcf/job/master/job/outerloop_windows_nt_UAP_release_prtest/1/console

I'll take another look tomorrow, we just need to determine whether it is some error in how I added the job, or if it something inherent with Jenkins not working with UAP (Jenkins machines maybe).

**Comment by StephenBonikowsky** [comment]
@mmitche do you know of anything with Jenkins that would be a problem with UAP? This isn't uapaot so no ILC stuff, I would expect it to just work.

**Comment by mmitche** [comment]
@StephenBonikowsky Nothing Jenkins related.  Do you want a machine to investigate?

**Comment by StephenBonikowsky** [comment]
Thanks @mmitche I'm going to be oof until the middle of next week, we weren't able to repro the issue locally so it may be a machine environment issue, I'll take you up on your offer when I get back.

In the mean time I'm leaving this PR as is but disabling the new job with PR #2182

**Pull request closed without merging**
