### PR TITLE
Fix issue with S.Reflection.Extensions being a fat pkg.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* See @ericstj commit for details...
https://github.com/dotnet/corefx/commit/3d7bdac4b02d42cbbf15d7ac164373c36d983a0f#diff-1cf61071aa9a8e298dd7972458ec9dcd

This should fix the issue we are seeing with PR #1540

### CODE REVIEW

**Comment by ericstj** [comment]
Why didn't you just make this change in the dotnet-bot PR?

**Comment by StephenBonikowsky** [comment]
I was wanting to make sure it worked without all the noise from that PR and if merged today that PR would get updated tomorrow morning with the new builds. I can add it there and close it here if it makes more sense to do so.

**Comment by ericstj** [comment]
You should do it there so that you can ensure it actually fixes the problem.

Also when doing this it's a good idea to manually run dotnet restore on the test-runtime project.json to confirm there are no warnings.

**Comment by StephenBonikowsky** [comment]
Ok, will do.

**Comment by StephenBonikowsky** [comment]
I got @roncain to edit the file with this change directly in PR #1540.

**Pull request closed without merging**
