### PR TITLE
Update pre release label

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
Also a little bit of cleanup plus updating the version of our netstandard and corefx dependencies.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@weshaggard I think these errors have something to do with 

> src\Common\test-runtime\project.json

 Wes, I'm trying a few things, do we need to add a runtime exclude for these failures under netcoreapp1.1 and netcoreapp2.0?

```
  Errors in C:\OSS\WCF\src\Common\test-runtime\project.json
      Unable to resolve 'runtime.fedora.23-x64.Microsoft.NETCore.TestHost (>= 2.0.0-preview1-25228-01)' for '.NETCoreApp,Version=v1.1 (fedora.23-x64)'.
      Unable to resolve 'runtime.fedora.23-x64.Microsoft.NETCore.Runtime.CoreCLR (>= 2.0.0-preview1-25228-01)' for '.NETCoreApp,Version=v1.1 (fedora.23-x64)'.
      Unable to resolve 'runtime.fedora.23-x64.Microsoft.NETCore.Jit (>= 2.0.0-preview1-25228-01)' for '.NETCoreApp,Version=v1.1 (fedora.23-x64)'.
      Unable to resolve 'runtime.fedora.23-x64.Microsoft.NETCore.TestHost (>= 2.0.0-preview1-25228-01)' for '.NETCoreApp,Version=v2.0 (fedora.23-x64)'.
```

**Comment by weshaggard** [comment]
We no longer support or build fedora.23 you should just remove it from your runtime list.

**Comment by StephenBonikowsky** [comment]
Addin @MattGal 
No validation errors and everything built, but tests are failing without any logs, they aren't producing any testResults.xml
Running CoreRun.exe manually produces nothing, no error, no logs, nothing. Attempting to debug CoreRun.exe with VS same thing, appears to run without any errors or logging.

Any ideas?

**Comment by StephenBonikowsky** [comment]
Not sure if this is significant, but when @weshaggard first added `<StandardExpectedPrerelease>` neither _Microsoft.NETCore.TestHost_ or _Microsoft.NETCore.Runtime.CoreCLR_ used that version they had a separate version. (see [Wes' PR])(https://github.com/dotnet/wcf/commit/8d13a14121643d7e9918075a1ea02a78c0acd057#diff-1cf61071aa9a8e298dd7972458ec9dcd)
Now when I update `<StandardExpectedPrerelease>` and run `msbuild build.proj /t:UpdateDependencies` those two packages are also getting updated in `test-runtime\project.json` I get validation errors if they don't.

@davis does it make sense that those two packages get updated and validated based on the version of `<StandardExpectedPrerelease>`?

**Comment by StephenBonikowsky** [comment]
Now I also see from the RunTests.cmd in the test bin that CoreRun.exe comes from Microsoft.NETCore.TestHost and it is RunTests.cmd that is failing so quietly.
`call :copyandcheck "%PACKAGE_DIR%\runtime.win7-x64.Microsoft.NETCore.TestHost\2.0.0-preview1-25228-01\runtimes\win7-x64\native\CoreRun.exe" "%EXECUTION_DIR%\CoreRun.exe" ||  exit /b -1`

**Comment by MattGal** [comment]
I have to head home now but will take a look when I can.

**Comment by zhenlan** [comment]
@MattGal, @weshaggard, @ericstj, any suggestions how we can get this PR pass?

**Comment by weshaggard** [comment]
This is just a hunch but I believe you also need to update the version of Microsoft.NETCore.App in test-runtime. Try updating it to the latest preview1 build "2.0.0-preview1-002104-00"

**Comment by StephenBonikowsky** [comment]
Your hunch appears to be correct, it built and ran unit tests successfully for me locally.
Running scenario tests now, if they work I will update the PR.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop OSX

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
This is strange, when I first cleaned and ran locally using Microsoft.NETCore.App version 2.0.0-preview1-002104-00 all tests ran and passed.

After updating the PR most of the checks passed, it failed outerloop and innerloop on OSX and outerloop on Windows selfhost. So I reran and now everything is failing. Back on my local environment I cleaned and tried to run and now I am getting...

`error : Exact package 'Microsoft.NETCore.App 2.0.0-preview1-002104-00' was not restored: found '2.0.0-preview2-002062-00'`

I can see this package does exist on [myget](https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.App), investigating.

**Comment by StephenBonikowsky** [comment]
I refreshed myget and now that build version has disappeared...
I will try using version 002101-00 instead.

**Comment by weshaggard** [comment]
>I will try using version 002101-00 instead.

Yes please do. I know some folks are doing some build testing perhaps they deleted some packages as part of that.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop OSX

**Comment by StephenBonikowsky** [comment]
Still seeing some of these for OSX...

`[ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/tests/**/testResults.xml'. Configuration error?`

**Comment by weshaggard** [comment]
The real error looks to be:
```
/corerun xunit.console.netcore.exe System.ServiceModel.Duplex.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp2.0tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
13:52:52   dlopen failed to open the libcoreclr.so with error dlopen
```
I think you need to update your netci.groovy script to start running on OSX 10.12. See https://github.com/dotnet/standard/commit/7915c2c4cc22f6df3b3ac5de23d74bf9fb0688cb where I did that for the standard repo recently.

**Comment by StephenBonikowsky** [comment]
Not sure what the problem is with OSX, because we need to get packages built I'm going to merge. Also want to see if tests on OSX fail in Helix.

**Comment by StephenBonikowsky** [comment]
Thanks Wes, will do that.

**Pull request merged**
