### PR TITLE
Updating folders and content for Scenario TransportSecurity tests.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Solution folders were missing and/or did not contain all the files.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by roncain** [comment]
Sorry -- I missed seeing something in #1144 that I should have caught, and it's in this one too.  The SLN file now contains links to .cs files, and it shouldn't.  I'm not sure what caused that (were they added to the SLN manually?), but the solution folders under tests\scenarios should contain only the .csproj files.  The .csproj's are the ones that supply the list of .cs files.  I think it is probably a matter of using VS to open the SLN and removing them (not deleting them) from the SLN folders.

**Comment by StephenBonikowsky** [comment]
I'll try that.

**Comment by StephenBonikowsky** [comment]
Amended with Ron's feedback and rebased to recent merges.

**Comment by roncain** [comment]
LGTM

**Pull request merged**
