### PR TITLE
Upgrade dotnet cli to take win7 fix

### PR DESCRIPTION
**Pull request by dagood**
More details at https://github.com/dotnet/corefx/pull/7376

/cc @joshfree @stephentoub

### CODE REVIEW

**Comment by roncain** [comment]
@dagood -- question. Will this version bring in the --infer-runtimes switch for the RID inference changes?
/cc @davidfowl, @joshfree, @stephentoub

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by roncain** [comment]
LGTM.
The CI failure requires investigation but looks like there are infrastructure issues.  I buddy-built and tested innerloops and outerloops on Windows and Ubuntu.  I did not verify in TFS because the latest enlistment doesn't build.  Merging now to stay in parity with CoreFx.

**Comment by dagood** [comment]
@roncain The threshold for `--infer-runtimes` was passed in https://github.com/dotnet/wcf/pull/950 and I added the switch there. Sorry I didn't cc you on that--I was just making PRs for all applicable repos to try to get rid of that break.

**Pull request merged**
