### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by roncain**
Remove types not in public contract that are not used.
This is part of a cleanup pass for code coverage analysis.

### CODE REVIEW

**Comment by roncain** [comment]
Reviewers: I'm analyzing code coverage pending adding more test coverage.  The code removed in this PR was not used (and not in any public API).

**Comment by zhenlan** [comment]
@roncain can you check the usage data of these APIs? They may have high usage in Framework/Xamarin but not flagged in previous usage analysis because they are already in implementation.

**Comment by roncain** [comment]
Good point @zhenlan -- I should verify usage before proceeding.  Labelled **PR DO NOT MERGE** to put this on the back burner while other higher priority tasks are handled first.

**Comment by roncain** [comment]
I'm going to close this PR and not merge it. Some of the dead code could be reached by API's we have not yet exposed.  The cost of understanding it sufficiently does not warrant doing this work now.

**Pull request closed without merging**
