### PR TITLE
Fix tests hanging waiting for async responses.

### LINKED ISSUE #2124: Client.ChannelLayer.Tests hanging
At least two tests...
RequestReplyChannelShapeTests.IRequestChannel_Async_Http_CustomBinding()
DuplexChannelShapeTests .IDuplexSessionChannel_Async_Tcp_NetTcpBinding()

Are hanging waiting for a response in asynchronous awaits.

While the exact problem is not understood, we do know that this only fails on 1 or 2 core test machines but not on our local machines that have more than 2 cores.

The workaround is to force these tests to not run in parallel.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Force these tests to not run in parallel.
* Fixes #2124

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Doing a test run right now to verify the fix in VSTS.

**Comment by MattGal** [comment]
Seems fine assuming you tried it and made sure this made it into the script.  If you end up need this in > 1 test though you'll want to put this property inclusion into your dir.props and make this a single well-named-property a la "<DisableParallelTestExecution>true..."

**Comment by StephenBonikowsky** [comment]
I confirmed it was in the RunTests.cmd for that test project.

**Comment by sharwell** [comment]
Can this property be configured via app.config and/or an assembly attribute instead?

**Comment by StephenBonikowsky** [comment]
I haven't really seen either of those two methods used in the NetCore infrastructure. @MattGal ?

**Comment by MattGal** [comment]
I don't think app.config works here since this is a .NET Core executable so System.Configuration is radically different and the exe in question is technically dotnet.exe / corerun.exe

There is [assembly: CollectionBehavior(DisableTestParallelization = true)] which you could experiment with, but AFAIK no CoreFX tests use this currently.

The thing to note here is that the .NET Core XUnit we're currently using is both old (written before XUnit had their own core port) and customized (to handle running in versions of .NET Core where certain APIs may throw or be missing).  So, YMMV with getting the assembly-level attribute to work.

**Pull request merged**
