### PR TITLE
Update buildtools to take fix for coverage issue.

### PR DESCRIPTION
**Pull request by crummel**

### CODE REVIEW

**Comment by crummel** [comment]
@roncain This should fix the coverage issue.

**Comment by roncain** [comment]
Thanks @crummel -- I'm doing a code coverage run using this patch right now to try it out.

**Comment by StephenBonikowsky** [comment]
Once CI passes we should be good to merge.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Pull request merged**
