### PR TITLE
April11 script sync

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
First part of syncing our build related scripts to corefx.
There are many changes and I found that syncing PR by PR was the best way.
This allows me to test each PR and when some change causes an issue or looks suspect I can skip that PR and do others ones.
All of these corefx PRs built for me and I would like to merge if possible so that tomorrow I can keep going with the remaining PRs and some other outstanding issues.
* Note: Rebasing removed some parts of some PRs, they are making so many changes that one person's changes one week are removed or modified the next.

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test, test Innerloop OSX Release Build and Test

**Comment by iamjasonp** [comment]
Question only: 
Should we copy over https://github.com/dotnet/corefx/pull/7056/files - `UpdateDependencies.ps1` as well? 

> This script updates all the project.json files with the latest CoreFX build version,
> and then creates a Pull Request for the change.

Seems like it could be useful for this repo too; otherwise we can just keep it in mind and do a copy over every time we want to use it without committing it to our own repo.

**Comment by iamjasonp** [comment]
Any need for us to add the AssemblyVersionTransition from PR 7135?

**Comment by iamjasonp** [comment]
From PR 7420 - publish-packages.cmd and publish-packages.sh required to be copied?

**Comment by iamjasonp** [comment]
LGTM. I think we'll need to do a TFS build with these changes too to confirm it doesn't break in TFS in unexpected ways.

**Comment by roncain** [comment]
I am doing a test build under TFS now... will update with results.

**Comment by iamjasonp** [comment]
+1. TFS build was successful for me. Please feel free to merge and take the questions post-merge

**Comment by iamjasonp** [comment]
Also, the innerloop OSX build issue is intermittent when restoring build tools. I'm not concerned about that.

**Comment by StephenBonikowsky** [comment]
UpdateDependencies.ps1 - Yes but didn't include it with this PR because initially I was focused on syncing the shared files, and I wasn't sure if we wanted to include it until we tried it to see if it works for us.
AssemblyVersionTransition - Not sure, I missed that, will follow up with Stephen Toub.
 PR 7420 - Not sure if we will publish packages from our repo.

**Comment by zhenlan** [comment]
> Not sure if we will publish packages from our repo

This should be the goal eventually.

**Pull request merged**
