### PR TITLE
Unit test for SecurityBindingElement.KeyEntropyMode.

### PR DESCRIPTION
**Pull request by imcarolwang**
For #3860. 

@StephenBonikowsky , @mconnew , @HongGit

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Looks good to me, the default value is the same as on full framework.

**Comment by imcarolwang** [comment]
@StephenBonikowsky  this was not merged and I happen to found I am able to do the merge operation, so I merged it ...

**Comment by StephenBonikowsky** [comment]
In this case that's fine, but for future PRs I want to get Matt's signoff as well. So if you have a PR that both he and I have approved and the checks are green then go ahead and merge.

You also need to do a couple other things once you merge which it looks like you did in this case...
   - move the related work item to the 'Scenario Tests' pipeline.
   - edit the description and check off the unit test field.
   - un-assign the work item

Thanks!

**Comment by imcarolwang** [comment]
Ok :)

**Pull request merged**
