### PR TITLE
Code formatter and update header

### LINKED ISSUE #1128: Rerun code formatter and update header of source code

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
In 3 commits...
1. Copyright updated for test, common and tools projects only.
2. Copyright updated for source files.
3. CodeFormatter rule 'ReadonlyFields'.

Only one of the rules actually caught anything, these are the rules...
#### Name  &ensp;&ensp;&ensp;&ensp;&ensp;&ensp; Description
BraceNewLine         :Ensure all braces occur on a new line
UsingLocation        :Place using directives outside namespace declarations
UnicodeLiterals      :Use unicode escape sequence instead of unicode literals
ExplicitVisibility   :Ensure all members have an explicit visibility modifier
ExplicitThis         :Remove explicit this/Me prefixes on expressions except where necessary
ReadonlyFields       :Mark fields which can be readonly as readonly
FieldNames           :Prefix private fields with _ and statics with s_

Fixes #1128

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Do we want to run the formatting rules against all test/common/infrastructure code as well?

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by zhenlan** [comment]
CodeFlow shows TcpTransportBindingElement.cs was edited but identical. This may be just an issue with CodeFlow when there are so many files updated. I just double check. Other than that, I looked all other changes and they LGTM.

**Comment by mconnew** [comment]
CodeFlow isn't showing all the changes. If you look at the [diff](https://github.com/dotnet/wcf/pull/1141.diff) file for this change, and search for the file, you will see the copyright was updated.

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by iamjasonp** [comment]
There's been some issues with CI; I've taken a quick look and I think we are back in a good state now. Awaiting Outerloop Windows_NT results before popping the champagne...

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Windows_NT

**Comment by roncain** [comment]
@StephenBonikowsky -- is it possible to get the outstanding PR's merged first?   This will likely cause merge conflicts in all of the existing PR's?

**Comment by roncain** [comment]
Yes, but please let's get the currently open PR's merged first.

---
In reply to: [218326176](https://github.com/dotnet/wcf/pull/1141#issuecomment-218326176) [](ancestors = 218326176)

**Comment by roncain** [comment]
Question only (and non-blocking no matter the answer) -- do you get any other changes if you run this against the NET Native conditionals?  I'm looking at this code in the main .csproj:
```
  <PropertyGroup Condition="'$(TargetGroup)' == 'netcore50'">
    <DefineConstants>$(DefineConstants);FEATURE_NETNATIVE</DefineConstants>
  </PropertyGroup>
``` 
No need to deal with this now, but worth an experiment when we do the 2nd pass against test and infra projects.

**Comment by roncain** [comment]
LGTM

**Pull request merged**
