### PR TITLE
Upgrade dependency pkg version to address security vulnerability.

### PR DESCRIPTION
**Pull request by imcarolwang**
For #5190. 
The vulnerabilities are also reported in ci pipeline. 

Cc: @mconnew , @HongGit

### CODE REVIEW

**Comment by HongGit** [comment]
@imcarolwang  we will wait for a secure version of System.Security.Cryptography.Xml.

**Comment by MoSelem** [comment]
> @imcarolwang we will wait for a secure version of System.Security.Cryptography.Xml.

is 7.0.1 not a secure version?

**Comment by imcarolwang** [comment]
> > @imcarolwang we will wait for a secure version of System.Security.Cryptography.Xml.
> 
> is 7.0.1 not a secure version?

It appears that 7.0.1 version of `System.Security.Cryptography.Xml` relies on `System.Security.Cryptography.Pkcs` (>= 7.0.0) , and 7.0.0 version of `System.Security.Cryptography.Pkcs` has the same severity vulnerability. So we still need to wait.

**Comment by MoSelem** [comment]
> 

I think the vulnerability exists in version 7.0.0 for only Net7,
WCF is releasing for Net6 only so far, and the vulnerability would be in Pks >=6.0.0 and <= 6.0.2, and the patched version is 6.0.3, 
so maybe version 7.0.0 for Net6 is fine?

**Comment by MoSelem** [comment]
> > 
> 
> I think the vulnerability exists in version 7.0.0 for only Net7, WCF is releasing for Net6 only so far, and the vulnerability would be in Pks >=6.0.0 and <= 6.0.2, and the patched version is 6.0.3, so maybe version 7.0.0 for Net6 is fine?

@imcarolwang

**Pull request closed without merging**
