### PR TITLE
[release/1.0.0] Update buildtools to add Serviceable to nupkgs

### PR DESCRIPTION
**Pull request by ericstj**
This also requires an update to all tests to use the NETCoreApp1.0
moniker.

/cc @joshfree @weshaggard @roncain @StephenBonikowsky

### CODE REVIEW

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by roncain** [comment]
@dotnet-bot test all outerloop please

**Comment by roncain** [comment]
FYI -- I've manually run OuterLoops same-machine-self-hosted as well as cross-machine-self-hosted and have not seen any errors.  I believe the CI OuterLoop failures for anything other than self-host reflect only our own infrastructure issues, not anything to do with this PR.

**Comment by ericstj** [comment]
Hold off on merging we found a NuGet regression here.  You aren't hitting it at the moment because you've disabled packaging on Unix, but I want to get you on the same version of BuildTools as corefx.

**Comment by ericstj** [comment]
Ok, that's been fixed.

**Pull request merged**
