### PR TITLE
Implement WebSockets

### PR DESCRIPTION
**Pull request by mconnew**

### CODE REVIEW

**Comment by mconnew** [comment]
@dotnet-bot retest this please

**Comment by iamjasonp** [comment]
This is a large PR, and as long as it builds and doesn't fail TFS builds, I'm okay with merging this first and writing tests against it. @roncain, thoughts?

**Comment by roncain** [comment]
Agree @iamjasonp -- merge now and deal with PR comments post-beta8. It has now been merged.  I believe @StephenBonikowsky and @mconnew will coordinate which new (if any) websockets tests will be added post-beta8

**Comment by StephenBonikowsky** [comment]
There's a build issue with the scenario test included in the PR, it will fail to build. Working on it.

**Pull request merged**
