### PR TITLE
Update buildtools version to rc1-03131-06 for release/2.1.0.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* The auto update PR failed due to Jenkins machines missing the expected version of msbuild.
* This was a breaking change in buildtools https://github.com/dotnet/buildtools/pull/2152
* The solution was to specifically use machine queues known to have the correct version installed.
* This was done in https://github.com/dotnet/wcf/pull/3175

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@Chrisboh I'm wondering how many machines are in the Win10 queue we are using for our CI now? This PR has been waiting on the Windows runs now for over 2 hours and still seem far down the queue.

**Comment by Chrisboh** [comment]
@StephenBonikowsky that is really odd.  There are only 7 jobs left in the queue and 30+ machines ready for work.  I asked @MattGal to take a look.

**Comment by StephenBonikowsky** [comment]
Thank you!

**Comment by StephenBonikowsky** [comment]
Rebased after merging #3178

**Comment by MattGal** [comment]
@Chrisboh  quick summary: We accidentally gave the wrong queue id (it had a hyphen) so no machines were provisioning at all.  Hopefully this will work after the PR I made above.

**Comment by StephenBonikowsky** [comment]
@MattGal 
I'm getting several of these...
`11:01:41 ERROR: Issue with creating launcher for agent windows.10.amd64.clientrs4.devex.15.8.open-0924110124338-0. The agent has not been fully initialized yet
11:01:41 Building remotely on windows.10.amd64.clientrs4.devex.15.8.open-0924110124338-0 (a0000G0) (windows.10.amd64.clientrs4.devex.15.8.open)ERROR: windows.10.amd64.clientrs4.devex.15.8.open-0924110124338-0 (a0000G0) seems to be offline`

**Comment by StephenBonikowsky** [comment]
I don't want to just spam re-runs on the machines, recommendation?

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test innerLoop Windows_NT

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by MattGal** [comment]
@StephenBonikowsky I'd suggest that you spam away and if you keep hitting issues, just open an FR one on dotnet/core-eng.

**Comment by StephenBonikowsky** [comment]
OSX failures are expected and the inner loop windows failures are because the change in netci.groovy in this PR has to be merged first.

Merging.

**Pull request merged**
