### PR TITLE
Adding tests for WebSockets

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
Currently failing due to Issue #275

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot retest this please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot retest this please

**Comment by roncain** [comment]
LGTM after it is rebased with recent changes and passes CI tests.
Nit: a few files don't have a final end-of-line but don't block on that.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot retest this please

**Pull request merged**
