### PR TITLE
Upgrade CLI, buildtools for RTM shared framework

### PR DESCRIPTION
**Pull request by dagood**
See https://github.com/dotnet/corefx/pull/11387. This buildtools change requires a CLI update at the same time, so I'm pushing it through to avoid pain later. I don't think this is urgent in WCF, it will just be necessary when a version of buildtools past this point is needed.

/cc @roncain

### CODE REVIEW

**Comment by iamjasonp** [comment]
LGTM, but I defer to @StephenBonikowsky or @roncain for final ACK

**Comment by iamjasonp** [comment]
@dotnet-bot test this please

**Comment by iamjasonp** [comment]
@dotnet-bot test InnerLoop Ubuntu14.04

**Comment by roncain** [comment]
Thanks @dagood .  Do we understand why we see the failures we do? It looks like we have failures across *nix (except for OSX) for both InnerLoops and OuterLoops that look like the log info below.

I know @StephenBonikowsky is currently working on syncing with CoreFx, so I defer to his thoughts on what parts of this to fix/merge and what parts he is working on.

```
03:32:42 [ubuntu14.04_release_prtest] $ /bin/sh -xe /tmp/hudson5132762323034715230.sh
03:32:42 + HOME=/mnt/j/workspace/dotnet_wcf/master/ubuntu14.04_release_prtest/tempHome ./build.sh /p:ShouldCreatePackage=false /p:ShouldGenerateNuSpec=false /p:OSGroup=Linux /p:ConfigurationGroup=Release
03:32:43 Setting up directories for build
03:32:43 Installing dotnet cli...
03:32:48 tar: This does not look like a tar archive
03:32:48 tar: Exiting with failure status due to previous errors
03:32:48 Restoring BuildTools version 1.0.26-prerelease-00802-07...
03:32:48 /mnt/j/workspace/dotnet_wcf/master/ubuntu14.04_release_prtest/init-tools.sh: line 78: /mnt/j/workspace/dotnet_wcf/master/ubuntu14.04_release_prtest/Tools/dotnetcli/dotnet: No such file or directory
03:32:48 
ERROR: Could not restore build tools correctly. See '/mnt/j/workspace/dotnet_wcf/master/ubuntu14.04_release_prtest/init-tools.log' for more details.
```

**Comment by StephenBonikowsky** [comment]
There is some issue restoring build tools on Linux.
I am working on a large PR to catch up with CoreFx in using the new DevWorkflow, I'd like to complete than and either incorporate these changes into it or address this right after it.

**Comment by dagood** [comment]
It looks like my email client wasn't working this morning so I didn't notice your comments, sorry about that.

The init-tools issues are known and I'm looking into them in the corefx PR--I'll close this issue and either reopen or create a new one when it's ok over there. Basically the problem is that CLI changed the SDK package layout. There's also an issue that would show up in the official builds of the packages being incompatible with some new platforms. (I tested this change on Windows and OSX, unfortunately the two unaffected platforms.)

@StephenBonikowsky I'd say don't worry about this change, since it's not even in corefx yet, and it should be a non-functional change for WCF.

**Pull request closed without merging**
