### PR TITLE
Update project.json files to package version rc2-23712

### PR DESCRIPTION
**Pull request by iamjasonp**
* Allows us to pull in NegotiateStream packages

@roncain - is there still a need to update the project.lock.json files, or is the need already gone? I ran the usual update commands and got no file changes. I will build in TFS with these changes to see what we get.

### CODE REVIEW

**Comment by roncain** [comment]
LGTM.
@dagood recently made changes to remove the project.lock.json files, so there is no need to update them.  The .gitignore prevents them from being checked in now anyway.
@StephenBonikowsky -- do you have any issues with this PR going in before you have package projects working?
I think this PR will probably merge okay with my #683 so feel free to go before me.

**Comment by iamjasonp** [comment]
Ah, excellent. Annoyingly I still had project.lock.json littered on my filesystem but I confirm that I don't see them anymore after cleaning them out manually.

**Comment by StephenBonikowsky** [comment]
I think it should be ok, not sure what effect the expected prerelease version change will have.

**Comment by iamjasonp** [comment]
Built in TFS enlistment and looks fine - couldn't verify this using the rolling lab builds, they be broken. Merging so we can all make further progress.

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by StephenBonikowsky** [comment]
:shipit:

**Comment by roncain** [comment]
Expect 1 OuterLoop test failure already known. Don't block merge on it.

**Comment by iamjasonp** [comment]
Excellent. Outerloop passes all but 1 test (known failure). Merging.

**Pull request merged**
