### PR TITLE
Update packages to rc3-23915

### PR DESCRIPTION
**Pull request by ericstj**
Update packages to rc3-23915

Update crypto dependencies

System.Security.Cryptography.Algorithms and
System.Security.Cryptography.X509Certificates have updated their
versions to 4.1 and now target both NETStandard1.3 and
NETStandard1.4.

Update references to these packages and update any project that is
restoring for DNXCore50 but packaging as NETStandard to restore for
NETStandard as well so that it gets the correct references.

### CODE REVIEW

**Comment by roncain** [comment]
Thanks @ericstj -- I'll buddy build this in TFS in addition to the CI runs.

**Comment by roncain** [comment]
@dotnet-bot test outerloop please

**Comment by roncain** [comment]
I'm getting this error in OuterLoop build and test and am investigating...
```
Could not load file or assembly 'System.IO.Compression, Version=4.1.0.0
```

**Comment by StephenBonikowsky** [comment]
Looks like the issue is "System.Xml.ReaderWriter", in our scenario .json files we are using the last stable version "4.0.0", the log files complain about a version conflict for this package. Updating it to "4.0.11-rc3-23915" in just one of the test .json files is enough to pull down the right set of packages, including the correct one for System.IO.Compression.

Before merging I just want to understand what caused the version bump.

**Comment by ericstj** [comment]
Something is downgrading System.IO.Compression 4.1 > 4.0.

**Comment by ericstj** [comment]
Caused by https://github.com/dotnet/corefx/commit/9b8403541bfbd4b1956944723b68167ad12fbf29 which upgraded dependency on Compression in WinHttpHandler.

**Comment by StephenBonikowsky** [comment]
Merging this and following quickly with another PR to fix the version of S.IO.Compression

**Pull request merged**
