### PR TITLE
Remove setting timer to null as it may be accessed in race condition of read/write callback and Abort

### LINKED ISSUE #1153: AV in System.ServiceModel.Channels.CoreClrSocketConnection.OnSendAsync
Another race condition. Looks like the timer is already disposed and nulled out.
Here is the relevant stack:

~~~
00000081ef04f7d0 00007ffb8b3fbeaf System.ServiceModel.Channels.CoreClrSocketConnection.OnSendAsync(System.Object, System.Net.Sockets.SocketAsyncEventArgs) [D:\git\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CoreClrSocketConnection.cs @ 448]
00000081ef04f810 00007ffbe8fcd0e3 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
00000081ef04f880 00007ffb8b3fbb16 System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError, Int32, System.Net.Sockets.SocketFlags)
00000081ef04f8d0 00007ffb8b3fb3fd System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped*)

~~~

### PR DESCRIPTION
**Pull request by mconnew**
Fixes #1153

### CODE REVIEW

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by zhenlan** [comment]
@dotnet-bot test all outerloop please

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by roncain** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by roncain** [comment]
LGTM subject to getting a CI pass.
For reasons I don't understand, a rebase appears necessary to being this into sync with the WCF services against which the tests run.

**Comment by mconnew** [comment]
@dotnet-bot test all outerloop please

**Comment by roncain** [comment]
LGTM.  The NetHttps test failures on *nix are expected.

**Pull request merged**
