### PR TITLE
Allow addressable resource URIs

### PR DESCRIPTION
**Pull request by SajayAntony**
Part of a change which will enable listing all available resource of the bridge. 

```
$ curl -X  PUT http://localhost:44283/resource/WcfService.TestResources.BasicHttpResource -d .
{
   uri : "http://localhost:8081/BridgeAppDomain0/Basic"
}
```

### CODE REVIEW

**Comment by roncain** [comment]
I like this approach.  Let me buddy-build the OuterLoops.

**Comment by SajayAntony** [comment]
@roncain @iamjasonp  I've updated the PR To support listing out the resources . :scream: 

```
$ curl http://localhost:44283/resource
{
   BaseAddressResource : "http://localhost:44283/resource/WcfService.TestResources.BaseAddressResource",
   BasicAuthResource : "http://localhost:44283/resource/WcfService.TestResources.BasicAuthResource",
   BasicHttpResource : "http://localhost:44283/resource/WcfService.TestResources.BasicHttpResource",
   BasicHttpsResource : "http://localhost:44283/resource/WcfService.TestResources.BasicHttpsResource",

...  
   WebSocketTransportResource : "http://localhost:44283/resource/WcfService.TestResources.WebSocketTransportResource"
}
```

You can issue a `PUT` as follows - 
```
$ curl -X PUT http://localhost:44283/resource/WcfService.TestResources.BasicHttpResource -d {}
{
   uri : "http://localhost:8081/BridgeAppDomain0/Basic"
}
```

And `GET` a resource as follows  -  :boom: 
```
$ curl http://localhost:44283/resource/WcfService.TestResources.BasicHttpResource
{
   uri : "http://localhost:8081/BridgeAppDomain0/Basic"
}
```

**Comment by SajayAntony** [comment]
@roncain Took a look at the failures in Release. It seems like a race between the Bridge.Task.sln and Bridge. I wonder if we could just have the task project in the bridge solution and have a build dependency or specify this in dirs. props or something else.

**Comment by iamjasonp** [comment]
Likely this will cause a merge conflict, but we can tease that together if we need to.

**Comment by SajayAntony** [comment]
@dotnet-bot  please retest this.

**Comment by SajayAntony** [comment]
@dotnet-bot please test this.

**Comment by iamjasonp** [comment]
@dotnet-bot retest this please

**Comment by SajayAntony** [comment]
@iamjasonp If you are ok with this let me know or feel free to merge the changes in. 
You might have you rebase. 
But this will also allow you to test the cert path using just curl of fiddler and give you all the resources etc. 

Error from the build logs. 
```
d:\j\workspace\dotnet_wcf\windows_release_prtest\src\System.Private.ServiceModel\tests\Common\Infrastructure\src\testproperties.targets(125,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Build.Tasks.Core.dll". Could not find file 'C:\Users\dotnet-bot\AppData\Local\Temp\05wiustf.dll'. [d:\j\workspace\dotnet_wcf\windows_release_prtest\src\System.Private.ServiceModel\tests\Common\Infrastructure\src\Infrastructure.Common.csproj]

```

**Comment by iamjasonp** [comment]
LGTM - we should just merge assuming it doesn't break the build. I can rebase on top of this.

**Pull request merged**
