### PR TITLE
Update buildtools and dotnet-cli version

### PR DESCRIPTION
**Pull request by iamjasonp**
* Upgrade dotnet CLI to 1.0.0-rc2-002468
* Update buildtools to v 1.0.25-prerelease-00321-01

This is synced to the current corefx versions. This update is needed also to allow code coverage to work again and to allow the OSX builds to build more consistently.

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop Windows_NT, test outerloop Ubuntu14.01, test outerloop OSX

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Windows_NT

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop OSX Release

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please

**Comment by iamjasonp** [comment]
@dotnet-bot test code coverage please

**Comment by iamjasonp** [comment]
Woohoo! Clean build. Please review

**Comment by roncain** [comment]
LGTM.
Agree we should sync to CoreFx versions like this asap.

**Comment by zhenlan** [comment]
> @dotnet-bot test outerloop Windows_NT, test outerloop Ubuntu14.01, test outerloop OSX

Where is Ubuntu outerloop from CI results? ...and I wish I don't have to put 14.01 there 😄.

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop osx, test outerloop ubuntu14.04

There's other ubuntu versions, that's why we specify a version here :smile:

**Comment by zhenlan** [comment]
Then I wish "test outerloop ubuntu" would test on all ubuntu versions 😄. Anyway, that's a different discussion.

**Comment by zhenlan** [comment]
Now that Ubuntu outerloop results show up, this LGTM.

**Comment by iamjasonp** [comment]
The groovy file is much simpler without special casing OSes... let's solve that particular problem if it's something more than just an inconvenience to your preference for typing less :smile: 

Merging now

**Comment by zhenlan** [comment]
I know it's a separate discussion. Just to respond your last comment:

> let's solve that particular problem if it's something more than just an inconvenience to your preference for typing less

It's not about typing less. It's about remembering the right number (version). You just showed a very good example in this thread that you have to change the number from 14.01 to 14.04 for this magic trigger to work.

**Comment by iamjasonp** [comment]
@zhenlan - I'll do you one better, I think. Stand by for a PR that will improve this experience :)

**Pull request merged**
