### PR TITLE
Update package version dependencies

### PR DESCRIPTION
**Pull request by roncain**
Updates project.json files to use the the latest beta versions
of packages, using a wildcard to be more flexibile in the future.

Added explicit some new System.Reflection.Emit dependencies that
appear to be necessary now (copied from CoreFx repo)

The project.lock.json files were updated automatically using:
    msbuild /t:RestorePackages /p:LockDependencies=true

### CODE REVIEW

**Comment by hongdai** [comment]
LGTM.

**Comment by roncain** [comment]
@dotnet-bot test this please

**Comment by iamjasonp** [comment]
LGTM

**Comment by roncain** [comment]
@dotnet-bot test this please

**Pull request merged**
