### PR TITLE
Update baseline version of CoreFx packages for ns 1.3.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* For System.Reflection.DispatchProxy and System.Security.Principal.Windows.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
The System.Private.ServiceModel.nuspec generated locally with these changes...

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="2.12">
    <id>System.Private.ServiceModel</id>
    <version>4.4.0-preview2-25318-0</version>
    <title>System.Private.ServiceModel</title>
    <authors>Microsoft</authors>
    <owners>microsoft,dotnetframework</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>https://github.com/dotnet/wcf/blob/master/LICENSE.TXT</licenseUrl>
    <projectUrl>https://dot.net/</projectUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <description>Internal implementation package not meant for direct consumption.  Please do not reference directly.  Provides implementation of System.ServiceModel packages. 
0a1232d019b5837bfa34cc410b3d8166ffb1b84e 
When using NuGet 3.x this package requires at least version 3.4.</description>
    <releaseNotes>https://go.microsoft.com/fwlink/?LinkID=799421</releaseNotes>
    <copyright>© Microsoft Corporation.  All rights reserved.</copyright>
    <serviceable>true</serviceable>
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.NETCore.Platforms" version="2.0.0-preview2-25304-02" />
        <dependency id="NETStandard.Library" version="1.6.1" />
        <dependency id="System.Collections.NonGeneric" version="4.3.0" />
        <dependency id="System.Collections.Specialized" version="4.3.0" />
        <dependency id="System.ComponentModel.EventBasedAsync" version="4.3.0" />
        <dependency id="System.Linq.Queryable" version="4.3.0" />
        <dependency id="System.Net.NameResolution" version="4.3.0" />
        <dependency id="System.Net.Security" version="4.3.0" />
        <dependency id="System.Net.WebHeaderCollection" version="4.3.0" />
        <dependency id="System.Net.WebSockets" version="4.3.0" />
        <dependency id="System.Net.WebSockets.Client" version="4.3.0" />
        <dependency id="System.Reflection.DispatchProxy" version="4.3.0" />
        <dependency id="System.Reflection.TypeExtensions" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Primitives" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Xml" version="4.3.0" />
        <dependency id="System.Security.Claims" version="4.3.0" />
        <dependency id="System.Security.Principal" version="4.3.0" />
        <dependency id="System.Security.Principal.Windows" version="4.3.0" />
        <dependency id="System.Xml.XmlDocument" version="4.3.0" />
        <dependency id="System.Xml.XmlSerializer" version="4.3.0" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.NETCore.Platforms" version="2.0.0-preview2-25304-02" />
        <dependency id="System.Net.Http.WinHttpHandler" version="4.4.0-preview2-25304-02" />
        <dependency id="System.Reflection.DispatchProxy" version="4.4.0-preview2-25318-0" />
        <dependency id="System.Security.Principal.Windows" version="4.4.0-preview2-25318-0" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by weshaggard** [comment]
What about 
`<dependency id="Microsoft.NETCore.Platforms" version="2.0.0-preview2-25304-02" />` Do you want to baseline that as well?

**Comment by zhenlan** [comment]
`Microsoft.NETCore.Platforms` does not have any dependencies (so it won't bring down other packages). I assumed 2.0.0 version is backward compatible with 1.1.0, but to be sure of compatibility it's probably good idea to baseline it as well. @weshaggard is this also your understanding  or did I miss some more important factors?

**Comment by ericstj** [comment]
All of our packages are backwards compatible so that's not anything unique to that package.  Again I think you should make a generic rule rather than special casing here.

**Comment by StephenBonikowsky** [comment]
After adding the full CoreFx baseline I get the below, does it matter that for ns2.0 it also drops the version of Microsoft.NETCore.Platforms?

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="2.12">
    <id>System.Private.ServiceModel</id>
    <version>4.4.0-preview2-25324-0</version>
    <title>System.Private.ServiceModel</title>
    <authors>Microsoft</authors>
    <owners>microsoft,dotnetframework</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>https://github.com/dotnet/wcf/blob/master/LICENSE.TXT</licenseUrl>
    <projectUrl>https://dot.net/</projectUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <description>Internal implementation package not meant for direct consumption.  Please do not reference directly.  Provides implementation of System.ServiceModel packages. 
67e6da0941c62892bf33697b0c98ae9157779e06 
When using NuGet 3.x this package requires at least version 3.4.</description>
    <releaseNotes>https://go.microsoft.com/fwlink/?LinkID=799421</releaseNotes>
    <copyright>© Microsoft Corporation.  All rights reserved.</copyright>
    <serviceable>true</serviceable>
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.NETCore.Platforms" version="1.2.0-preview2-25324-0" />
        <dependency id="NETStandard.Library" version="1.6.1" />
        <dependency id="System.Collections.NonGeneric" version="4.3.0" />
        <dependency id="System.Collections.Specialized" version="4.3.0" />
        <dependency id="System.ComponentModel.EventBasedAsync" version="4.3.0" />
        <dependency id="System.Linq.Queryable" version="4.3.0" />
        <dependency id="System.Net.NameResolution" version="4.3.0" />
        <dependency id="System.Net.Security" version="4.3.0" />
        <dependency id="System.Net.WebHeaderCollection" version="4.3.0" />
        <dependency id="System.Net.WebSockets" version="4.3.0" />
        <dependency id="System.Net.WebSockets.Client" version="4.3.0" />
        <dependency id="System.Reflection.DispatchProxy" version="4.3.0" />
        <dependency id="System.Reflection.TypeExtensions" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Primitives" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Xml" version="4.3.0" />
        <dependency id="System.Security.Claims" version="4.3.0" />
        <dependency id="System.Security.Principal" version="4.3.0" />
        <dependency id="System.Security.Principal.Windows" version="4.3.0" />
        <dependency id="System.Xml.XmlDocument" version="4.3.0" />
        <dependency id="System.Xml.XmlSerializer" version="4.3.0" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.NETCore.Platforms" version="1.2.0-preview2-25324-0" />
        <dependency id="System.Net.Http.WinHttpHandler" version="4.4.0-preview2-25324-0" />
        <dependency id="System.Reflection.DispatchProxy" version="4.4.0-preview2-25324-0" />
        <dependency id="System.Security.Principal.Windows" version="4.4.0-preview2-25324-0" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by weshaggard** [comment]
That spec looks wrong. The NS2.0 should reference the highest version for M.NC.Platforms. Also on the NS1.3 dependencies I don't know why that would have a prerelease label on it.

**Comment by ericstj** [comment]
Agreed.  It looks like the merge of the indexes isn't giving you the correct versions.  Its possibly a bug in https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageIndex.cs#L140.  I try to do the right thing here but its might be getting tripped up.  Have you pushed the latest changes?

**Comment by StephenBonikowsky** [comment]
I just updated it.

**Comment by ericstj** [comment]
I see, we haven't really tested this use case where a different repo lists packages that it doesn't build itself.  The corefx index gets stamped with a prerelease string before you consume it, so any non-stable packages get that pre-release version.  Your locally defined packages (which may overlap with data in the corefx index) get the pre-release value for your local build.  I think the fix here will be to allow for a later defined baseline to always win.  That way you can import baselines after all other indexes and not get the pre-release version assumed.

**Comment by StephenBonikowsky** [comment]
Did you want me to do that?

**Comment by ericstj** [comment]
I think that's the smallest fix for this.  The other solutions I can think of all involve inventing some sort of custom merge logic and/or re-implementing baselining.  I put most of that merge logic in place with the goal of supporting WCF scenarios so it'd help if you had some familiarity with it.

**Comment by StephenBonikowsky** [comment]
I'm not opposed to a more 'correct' fix for our Master branch, for this PR into release/2.0.0 we need to complete all changes in the next couple of days.

My only concern with the buildtools change is unintentionally affecting other folks?

**Comment by weshaggard** [comment]
>My only concern with the buildtools change is unintentionally affecting other folks?

I would prefer a fix that doesn't require a buildtools update as we currently haven't forked a buildtools version that matches WCF yet, as you guys aren't able to consume the latest 2.0 buildtools.

**Comment by ericstj** [comment]
WCF is really the only place we rely on merging indexes.  So I'm not worried about it effecting others.

I hadn't realized WCF wasn't on the latest buildtools yet, that is problematic.

**Comment by ericstj** [comment]
If you want a safer fix then I'd just create a target that runs in the pkgproj AfterTargets GetNuGetPackageDependencies and just explicitly sets the version for the Dependency items you want to control.

**Comment by StephenBonikowsky** [comment]
I've just started the process of moving us to buildtoolsv2, we aren't expecting it to be completed very quickly though.

**Comment by StephenBonikowsky** [comment]
Ok, will do that.

**Comment by ericstj** [comment]
Assuming you do that, you'll undo all the index changes and the target will have some items that are conditioned to the ID (Identity of dependency item) and TargetFramework (metadata of same name) you want to change and overwrite the Version metadata to the version you want.

EG:
```xml
<ItemGroup>
  <Dependency Condition="'%(Identity)' == 'System.Foo' AND '%(TargetFramework)' == 'netstandard1.3'">
    <Version>4.3.0</Version>
  </Dependency>
</ItemGroup>
```

There might be a clever way to do this in a less brute force way but I can't think of anything at the moment.

**Comment by StephenBonikowsky** [comment]
Ok, just updated with the new change, the nuspec now looks like...
I left Microsoft.NETCore.Platforms alone.

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="2.12">
    <id>System.Private.ServiceModel</id>
    <version>4.4.0-preview2-25324-0</version>
    <title>System.Private.ServiceModel</title>
    <authors>Microsoft</authors>
    <owners>microsoft,dotnetframework</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>https://github.com/dotnet/wcf/blob/master/LICENSE.TXT</licenseUrl>
    <projectUrl>https://dot.net/</projectUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <description>Internal implementation package not meant for direct consumption.  Please do not reference directly.  Provides implementation of System.ServiceModel packages. 
498a2f6212defcc40ef6eca28bce80b21cc5126f 
When using NuGet 3.x this package requires at least version 3.4.</description>
    <releaseNotes>https://go.microsoft.com/fwlink/?LinkID=799421</releaseNotes>
    <copyright>© Microsoft Corporation.  All rights reserved.</copyright>
    <serviceable>true</serviceable>
    <dependencies>
      <group targetFramework=".NETStandard1.3">
        <dependency id="Microsoft.NETCore.Platforms" version="2.0.0-preview2-25304-02" />
        <dependency id="NETStandard.Library" version="1.6.1" />
        <dependency id="System.Collections.NonGeneric" version="4.3.0" />
        <dependency id="System.Collections.Specialized" version="4.3.0" />
        <dependency id="System.ComponentModel.EventBasedAsync" version="4.3.0" />
        <dependency id="System.Linq.Queryable" version="4.3.0" />
        <dependency id="System.Net.NameResolution" version="4.3.0" />
        <dependency id="System.Net.Security" version="4.3.0" />
        <dependency id="System.Net.WebHeaderCollection" version="4.3.0" />
        <dependency id="System.Net.WebSockets" version="4.3.0" />
        <dependency id="System.Net.WebSockets.Client" version="4.3.0" />
        <dependency id="System.Reflection.DispatchProxy" version="4.3.0" />
        <dependency id="System.Reflection.TypeExtensions" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Primitives" version="4.3.0" />
        <dependency id="System.Runtime.Serialization.Xml" version="4.3.0" />
        <dependency id="System.Security.Claims" version="4.3.0" />
        <dependency id="System.Security.Principal" version="4.3.0" />
        <dependency id="System.Security.Principal.Windows" version="4.3.0" />
        <dependency id="System.Xml.XmlDocument" version="4.3.0" />
        <dependency id="System.Xml.XmlSerializer" version="4.3.0" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.NETCore.Platforms" version="2.0.0-preview2-25304-02" />
        <dependency id="System.Net.Http.WinHttpHandler" version="4.4.0-preview2-25304-02" />
        <dependency id="System.Reflection.DispatchProxy" version="4.4.0-preview2-25304-02" />
        <dependency id="System.Security.Principal.Windows" version="4.4.0-preview2-25304-02" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by ericstj** [comment]
👍

**Pull request merged**
