### PR TITLE
Update xunit to version 2.1.0

### PR DESCRIPTION
**Pull request by iamjasonp**

### CODE REVIEW

**Comment by roncain** [comment]
@iamjasonp Please don't merge till we resolve dependency issue in beta8 with S.Net.Security.  I'm trying to make minimal touches to the json files to consider integrating forward into beta8

**Comment by iamjasonp** [comment]
Btw, this will fix the Xunit.Runner error issues we faced when updating our project.lock.jsons

@roncain - I'll wait until your OK to merge

**Comment by iamjasonp** [comment]
*Reminder:* if the change to move System.Net.Security down to the dnxcore50 { } section gets in before this is merged, please re-generate the project.lock.json files.

**Comment by roncain** [comment]
I buddy built this and ran it against both CoreCLR and NET Native tests.  LGTM.  Merging now to make headway on beta8 issues

**Pull request merged**
