### PR TITLE
dotnet-svcutil: add conditional reference to wcf dependency for multitarget project

### PR DESCRIPTION
**Pull request by imcarolwang**
For #5211.

**Description**

If user project's TargetFrameworks is combination of non-dnx and dnx version >= net6.0, dotnet-svcutil will conditionally reference to System.ServiceModel assembly for supported non-dnx framework target (such as net472, net48) and conditionally reference to wcf 6.0.* package for non-dnx target.

**Sample scenario validated**
1. `<TargetFrameworks>net48;net5.0;net6.0</TargetFrameworks>`
    `<TargetFrameworks>net48;net5.0</TargetFrameworks>`
Will add reference to wcf package 4.8.*, same as when target framework is net5.0
2. `<TargetFrameworks>net48;net6.0</TargetFrameworks>`
Will conditionally reference to System.ServiceModel assembly for net48 and reference 6.0.* wcf package for non-net48 target
3. `<TargetFrameworks>net5.0;net6.0;net7.0</TargetFrameworks>`
Will add wcf package version same with which added for lowest .NET core target in list, in this case it's wcf package version 4.8.*  
4. `<TargetFrameworks>net6.0;net7.0</TargetFrameworks>`
Will add wcf package version same with which added for lowest .NET core target in list, in this case it's wcf package version 6.0.*

### CODE REVIEW

**Comment by HongGit** [comment]
@imcarolwang can you please add test to validate csproj changes?

**Comment by HongGit** [comment]
@imcarolwang can you please add conditional compiled implementation of CloseAsync for .NET Framework?

Please also add test to validate csproj changes?

**Comment by imcarolwang** [comment]
> @imcarolwang can you please add conditional compiled implementation of CloseAsync for .NET Framework?
> 
> Please also add test to validate csproj changes?

I am working on the implementation.  I will update PR after the changes are validated.

**Comment by imcarolwang** [comment]
PR updated. Test scenario covered validation of wcf product reference generation in .csproj and CloseAsync() method generation in reference.cs.  The tests are manually performed since automation case is currently blocked due to Process.Start fail to create a csproj with required target framework.

**Comment by HongGit** [comment]
@imcarolwang we are not seeing the test scenario in the updated commit.  Is it possible to create test csproj, and update it?

**Comment by imcarolwang** [comment]
> @imcarolwang we are not seeing the test scenario in the updated commit. Is it possible to create test csproj, and update it?

Due to an existing test issue, it is a non-trivial work for me to automate the test scenarios soon, to unblock merge, we perform the tests manually, test scenarios can be found in Xiaolin's email.

**Review by HongGit — APPROVED** [review]

**Pull request merged**
