### PR TITLE
Testing netci.groovy file.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@mmitche things are looking much better now. The only test failure I see now is a test we have where we get the value of `TestProperties[TestNugetRuntimeId]` to do a comparison but it is returning as an empty string.
https://github.com/dotnet/wcf/blob/master/src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs#L126
Do you know if something has changed recently regarding this property?  The Windows runs passed because we do some additional parsing to get the OSID from the OSDescription which we don't do with non-Windows OSes.

**Comment by mmitche** [comment]
I don't.  @weshaggard Do you know whether anything interesting happened?

**Comment by weshaggard** [comment]
@StephenBonikowsky is this after the BuildTools 2.0 update? If so then yes we stopped using TestNugetRuntimeId so if you were expecting it to be set from BuildTools then it likely isn't any longer.

**Comment by StephenBonikowsky** [comment]
@weshaggard thanks, yes this is after the BuildTools 2.0 update. We extended Xunit's attribute functionality to give us additional conditional control of when we run tests, in WCF some features may not work on some specific OS. Looks like we used TestNugetRuntimeId to get this OS info, can you recommend some other property used in BuildTools 2.0 that would get us the same info?

**Comment by weshaggard** [comment]
I've not looked at all your BuidTools 2.0 changes but if you guys are using the configuration system like corefx then you should have a RuntimeOS property that should give you similar information. It is setup via https://github.com/dotnet/buildtools/blob/03988127f489bcd1cf58d71131ac628620d53de9/src/Microsoft.DotNet.Build.Tasks/GenerateConfigurationProps.cs#L137.

**Comment by StephenBonikowsky** [comment]
Thanks Wes!

**Pull request closed without merging**
