### PR TITLE
Port rc1 fixes

### PR DESCRIPTION
**Pull request by roncain**
Integrates these 2 PR's from master into 1.0.0-rc1 in preparation for RC1 stabilization
 https://github.com/dotnet/wcf/pull/455  and
 https://github.com/dotnet/wcf/pull/435

### CODE REVIEW

**Comment by roncain** [comment]
@mconnew, @iamjasonp @shmao -- this PR was created with help from @ellismg to effectively RI our PR's from master back into the rc branch he created.  Comments are welcome, but obviously please do not attempt to merge yet.  We will work with the RC1 shiproom to seek permission for this PR to be merged and then integrated to KRel.  I will buddy build this against KRel tonight and tomorrow morning.  If you are up to buddy building, it needs to be applied against a KRel enlistment.

**Comment by shmao** [comment]
Verified the changes done by https://github.com/dotnet/wcf/pull/435. LGTM.

**Comment by iamjasonp** [comment]
Built in OSS - inner/outerloop tests run fine, I'm pulling down a KRel enlistment for buddy building

**Comment by roncain** [comment]
WCF buddy-built correctly in a scorched ProjectKRel with this PR overlayed on top.  I built all of partitions.proj and saw build errors in other parts of NDP, but no errors in WCF.

All ToF tests passed in K, including OSS ones and legacy.  Most ToF tests passed against NET Native -- the failures being either https (known to fail in ToF) and those known to have been fixed in the toolchain.

LGTM too.

**Comment by roncain** [comment]
@shmao @iamjasonp @mconnew @ellismg -- be aware I added commit 3 to bring PR #460 into this RC1 branch.  That PR was necessary in master to prevent CrossGen.exe breakage due to the lack of S.R.S.Xml 4.1 in desktop.  I will rebuild and retest KRel.

**Comment by roncain** [comment]
@mconnew or @StephenBonikowsky or @hongdai or @zhenlan -- could I ask one of you to at least visually inspect that the changes in this PR match what was in #435, #455 and #460?  I plan to submit this to shiproom this morning.  Buddy building in KRel would also be a help, but I have done it twice.

**Pull request merged**
