### PR TITLE
Updating CoreFx dependency to version preview1-24530-04

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* CoreFx updated their official preview1 release to version preview1-24530-04, updating WCF to depend on this version.
* Updated the CoreClr hash in dependencies.props to match what is in the CoreFx version.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@leecow @Petermarcu @gkhanna79 
Can you approve this change for release/1.1.0? Do I need an additional e-mail?

**Comment by gkhanna79** [comment]
Yes, please send email.

**Comment by StephenBonikowsky** [comment]
Sent.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Pull request merged**
