### PR TITLE
Slight adjustment for clarification

### PR DESCRIPTION
**Pull request by robashton**
As in the title

### CODE REVIEW

**Comment by phillip-haydon** [comment]
I find this PR highly disappointing. It would have been better if you just deleted everything committed that. At least we would have achieved something. Cleaned up .NET.

**Comment by robashton** [comment]
Sorry @phillip-haydon - I really tried my hardest to improve the project with the time I had available

**Comment by roncain** [comment]
Nice. WTF is a bit overloaded as an acronym around the web services space so we'll probably keep with WCF for now.  Thanks for the suggestion though.

**Comment by robashton** [comment]
:up: I understand - thank you for taking the time to consider my request

**Comment by wayne-o** [comment]
👌 looking a-ok for the merge there rob. Would it be possible to uppercase the letters throughout for consistency as well as to ensure the semantics are clear?

**Comment by nosami** [comment]
@dotnet-bot merge this

**Comment by BhavO** [comment]
@wayne-o, looks like robs cleverly matched the original casing. 

Go go Pony power.

**Comment by robashton** [comment]
@BhavO @wayne-o I used a sensible OS that is case sensitive by default so this was never even an accidental concern ;)

**Comment by wayne-o** [comment]
Loving your work!

**Comment by robashton** [comment]
Attention to detail is what counts

**Comment by Agares** [comment]
Damn, I knew I wasn't the only one who thought about that.

**Pull request closed without merging**
