### PR TITLE
Test CI - Do not merge

### PR DESCRIPTION
**Pull request by hongdai**
Test CI to ensure the right PR service number is used

### CODE REVIEW

**Comment by hongdai** [comment]
The string match in the netci.groovy file does not seem to be working. For example, OuterLoop Windows_NT Debug is using WCF3, instead of WCF3XX. We will have PR

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
Test CI - Do not merge

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by hongdai** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
#1541, #1542, #1543 fixes the issue you're seeing where the correct PR service isn't used... thanks for catching this @hongdai!

**Pull request closed without merging**
