### PR TITLE
Improve certificate chain build validation

### PR DESCRIPTION
**Pull request by mconnew**
This is a security fix and its associated test.

### CODE REVIEW

**Comment by mconnew** [comment]
@dotnet-bot test outerloop

**Comment by mconnew** [comment]
@dotnet-bot test all outerloop

**Comment by mconnew** [comment]
@dotnet-bot test all outerloop

**Comment by mconnew** [comment]
@dotnet-bot test all outerloop

**Comment by mconnew** [comment]
@dotnet-bot test all outerloop

**Comment by mconnew** [comment]
@dotnet-bot test all outerloop

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Comment by mconnew** [comment]
@dotnet-bot test outerloop RHEL7.2

**Comment by zhenlan** [comment]
@dotnet-bot test all please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Pull request merged**
