### PR TITLE
Add test for xsfa

### LINKED ISSUE #1783: Add additional tests for XmlSerializerFormatAttribute
We need at least one scenario test.
We also need to add a unit test to validate the SupportFaults property, analyse if there is a scenario for this property as well.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
Fixes #1783

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@mmitche do you have any other ideas why the OSX runs are failing?
I made the changes in the other PR to use OSX 10.12 but it doesn't seem to have made any difference.
I have very little experience with Jenkins, could you point me in the right direction?

**Comment by mmitche** [comment]
@StephenBonikowsky The PR changing to OSX 10.12 was wrong (had incorrect name for the OS).  I'll fix.

**Comment by StephenBonikowsky** [comment]
Ah, thank you.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop OSX

**Comment by StephenBonikowsky** [comment]
@mmitche any other ideas?

**Comment by StephenBonikowsky** [comment]
Same error as before...
```
Commands:
         ./corerun xunit.console.netcore.exe System.ServiceModel.Duplex.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp2.0tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonosxtests
         dlopen failed to open the libcoreclr.so with error dlopen(/Users/dotnet-bot/j/workspace/dotnet_wcf/master/osx_debug_prtest/bin/tests/AnyOS.AnyCPU.Debug/System.ServiceModel.Duplex.Tests/netstandard2.0.netcoreapp2.0/libcoreclr.dylib, 6): Symbol not found: _clock_gettime
           Referenced from: /Users/dotnet-bot/j/workspace/dotnet_wcf/master/osx_debug_prtest/bin/tests/AnyOS.AnyCPU.Debug/System.ServiceModel.Duplex.Tests/netstandard2.0.netcoreapp2.0/libcoreclr.dylib (which was built for Mac OS X 10.12)
           Expected in: /usr/lib/libSystem.B.dylib
          in /Users/dotnet-bot/j/workspace/dotnet_wcf/master/osx_debug_prtest/bin/tests/AnyOS.AnyCPU.Debug/System.ServiceModel.Duplex.Tests/netstandard2.0.netcoreapp2.0/libcoreclr.dylib
```

**Comment by mmitche** [comment]
@StephenBonikowsky Looks like the job names changed, so look at the OSX10.12 runs towards the bottom.  Example: https://ci.dot.net/job/dotnet_wcf/job/master/job/outerloop_osx10.12_debug_prtest/1/

The other status checks will not appear on future PRs

**Comment by StephenBonikowsky** [comment]
I think I see, to test this I will close this PR and open a new one.

**Pull request closed without merging**
