### PR TITLE
Update buildtools 00412-03

### PR DESCRIPTION
**Pull request by ericstj**
This brings in buildtools version with update to packaging min version for nuget.

We now only pre-req nuget 2.12, but list 3.4 as a requirement for 3.x nuget clients in the package description.

### CODE REVIEW

**Comment by roncain** [comment]
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by StephenBonikowsky** [comment]
Merge after CI's pass and dotnet/corefx#8485 is merged.

**Comment by roncain** [comment]
@dotnet-bot test Innerloop Windows_NT Debug

Re-running -- a prior failure looked bogus.

**Pull request merged**
