### PR TITLE
Update shared files 5 23 2016

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
Porting 5 corefx PRs plus updating to latest build tools version.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Comment by StephenBonikowsky** [comment]
The one test failure on Ubuntu is a known test bug, @roncain will be fixing.

**Comment by StephenBonikowsky** [comment]
If anyone is willing to LGTM this please also just go ahead and merge it.

**Comment by roncain** [comment]
LGTM
The one failing test is a known flakey one I will fix separately.
I will merge this now per @StephenBonikowsky 's instructions

**Pull request merged**
