### PR TITLE
Modify InstallRootCertificate.sh to support OpenSUSE

### PR DESCRIPTION
**Pull request by iamjasonp**

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop opensuse13.2, test Outerloop opensuse13.2

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop opensuse13.2, test Outerloop opensuse13.2

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop RHEL7.2

**Comment by roncain** [comment]
LGTM, subject to a question about the CI failures.
I see this in the RHEL logs that appears to be the cause of the failure:
```
  WCF Core CA Certificate Installer
      Detected OS as: rhel
EXEC : warning : Could not find 'c_rehash'. Is OpenSSL installed properly? 
```
Is this expected?   If it is expected, then LGTM and don't block on this question.

**Comment by iamjasonp** [comment]
For RHEL, it looks like c_rehash hasn't been installed on the machine; there's potentially a separate certificate add mechanism which I'm digging into

I don't expect the RHEL runs to pass at the moment, but I didn't want to fork the script yet for a command that's as yet undetermined.

**Comment by iamjasonp** [comment]
Fixes #1401

**Comment by roncain** [comment]
LGTM
Agreed -- the RHEL issue should not block this PR.

**Pull request merged**
