### PR TITLE
PR for validating and fixing CI issues.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* PR #1989 updated the WCF Master branch to all the latest changes needed for buildtoolsv2.
* While this was validated on local environments netci.groovy file changes were necessary for CI.
* Using this PR to identify CI issues and fix them.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@mmitche I updated netci.groovy in #1995 which seemed to be the cause for the error we are seeing but I am still getting the same error.

[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/tests/**/testResults.xml'. Configuration error?.

Can you assist with this error, any ideas?

**Comment by mmitche** [comment]
@dotnet/dnceng For context

@StephenBonikowsky Actually, missed something in my review:

https://github.com/dotnet/wcf/pull/1995/files#diff-2d212ad84506951c8f928e21aed24580R227

and the other line should have double quoted strings.  In-line replacement doesn't take place on single quoted strings

**Comment by StephenBonikowsky** [comment]
@mmitche is there a way for me to get on the machines?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@StephenBonikowsky You missed one inline string.  Fixed in https://github.com/dotnet/wcf/pull/1998

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test ci please

**Pull request merged**
