### PR TITLE
Resource string cleanup

### PR DESCRIPTION
**Pull request by morganbr**
Automated cleanup of unused resources in System.Private.ServiceModel. This removes about 75% of the file or roughly 300kb from the binary. The automated tool scanned for source references to resource strings. Github's diffing is showing additions, but there are no actual additions or edits, just removals. Verification was build+unit tests.

### CODE REVIEW

**Comment by joshfree** [comment]
nice!

/cc @zhenlan @shmao

**Comment by morganbr** [comment]
cc @mconnew

**Comment by zhenlan** [comment]
Thanks @morganbr! Did the automated tool scan against binary or the source code? If it's the binary, as @mconnew mentioned offline, the Windows/Linux/UWP builds many have different references to the resources. Just want to make sure we don't miss anything.

**Comment by morganbr** [comment]
@zhenlan, the tooling ran against the source code in the System.Private.ServiceModel directory. It's just a regex, so it's not foolproof, but my hope is CI covered the various build flavors.

**Comment by zhenlan** [comment]
CI does not cover UWP and our code coverage is only ~30% so I don't trust tests that much.

**Comment by morganbr** [comment]
@Zhenlan, my base assumption here is that, like other CoreFX libraries, resources are always fetched via the SR class. If that's true, there should be a build failure if I removed any strings that were still needed. I did also do a local build as well and it looks like the netcore50 version of S.P.ServiceModel built correctly. Is that correct reasoning for System.Private.ServiceModel?

**Comment by morganbr** [comment]
Thanks for approving, @Zhenlan. I don't have merge access on the WCF repo, so feel free to merge on my behalf.

**Pull request merged**
