### PR TITLE
Disable event channel usage

### PR DESCRIPTION
**Pull request by mconnew**
This is needed because the channels are getting mixed up and we're
trying to send the wrong events to the wrong channels and this is
causing a performance problem.

Addresses #1217 but isn't the final solution as we need to get channels working.

### CODE REVIEW

**Comment by mconnew** [comment]
@ dotnet-bot test outerloop Ubuntu14.01, test outerloop Windows_NT

**Comment by zhenlan** [comment]
cc: @vancem

**Comment by zhenlan** [comment]
>             public const int DummyDebugEventId = 65533;

Do we still want to keep these dummy IDs?

---
Refers to: src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs:2635 in b1eb4d7. [](commit_id = b1eb4d76e32db9dfea2e66a29f9b90316c3c1681, deletion_comment = False)

**Comment by mconnew** [comment]
New iteration removing the Dummy Id's

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Ubuntu14.01, test outerloop Windows_NT

**Comment by mconnew** [comment]
Here's the performance improvements this gives:

Concurrent requests|Baseline rq/s|Fix rq/s
-------------------|-------------|--------
Tasks 1|1380|1457
Tasks 6|14521|18652
Tasks 11|32943|39346
Tasks 16|44282|50934
Tasks 21|47569|57164
Tasks 26|49775|59269
Tasks 31|29090|63413
Tasks 36|18623|63940
Tasks 41|24297|68023
Tasks 46|17521|68282
Tasks 51|16984|70477
Tasks 56|18096|72768
Tasks 61|15930|73135
Tasks 66|16256|74024
Tasks 71|15805|74512

**Comment by mconnew** [comment]
@vancem this is the change we're making for RTM to disable channels.

**Comment by iamjasonp** [comment]
Is there an issue tracking re-enablement of these traces? If yes, can you please advise on the issue number. 

Code LGTM.

**Comment by vancem** [comment]
I don't know of a issue tracking reenablment. 

As an aside, the pull request https://github.com/dotnet/coreclr/pull/5477  

will unblock the original fix https://github.com/dotnet/wcf/pull/1238 

which was abandoned for V1.0.0

**Comment by mconnew** [comment]
@vancem, I've retitled the original issue #1217 to track re-enabling the events and added a comment referencing the PR's which need to be reverted and reapplied.

**Pull request merged**
