### PR TITLE
Updating to package version 24109.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Currently getting errors related to System.Private.ServiceModel\tests\Common\Infrastructure\src\Infrastructure.Common.csproj.

### CODE REVIEW

**Comment by mconnew** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by iamjasonp** [comment]
LGTM subject to CI pass

**Comment by roncain** [comment]
@dotnet-bot test outerloop selfhost Windows_NT

**Comment by roncain** [comment]
LGTM too, subject to CI results.

**Comment by mconnew** [comment]
I had a look at the failure for the OuterLoop Windows_NT Debug check and it was an infrastructure issue. Jenkins lost it's connection to the runner just as the tests run was doing the cleanup step. All tests passed.

**Pull request merged**
