### PR TITLE
Add net6.0 support for dotnet-svcutil and update tests.

### PR DESCRIPTION
**Pull request by imcarolwang**
For #4766 .

### CODE REVIEW

**Review by HongGit — APPROVED** [review]

**Comment by mxa0079** [comment]
Ive cloned this branch and when I try to build the svcutil tool following the README instructions I get the following error:

/Users/username/.nuget/packages/microsoft.dotnet.arcade.sdk/6.0.0-beta.21370.12/tools/InstallDotNetCore.targets(15,5): error : dotnet-install failed [/Users/mad/.nuget/packages/microsoft.dotnet.arcade.sdk/6.0.0-beta.21370.12/tools/Tools.proj]

Am I doing something wrong? Am I missing anything? Or is this a bug?

**Comment by mxa0079** [comment]
Hello - any comments on this?

**Comment by imcarolwang** [comment]
@mxa0079  is it possible caused by the .NetCore SDK version in global.json (root dir of the repo) isn't installed on your build machine? You can give it a try to update that file with installed version and rebuild ...

**Comment by imcarolwang** [comment]
@mxa0079  is it possible caused by the .NetCore SDK version in global.json (root dir of the repo) isn't installed on your build machine? You can give it a try to update that file with installed version and rebuild ...

**Comment by imcarolwang** [comment]
@mxa0079  By the way, the code change in this PR has been merged so you can pull the latest code of main branch to see if issue persist.

**Pull request merged**
