### PR TITLE
Enable HttpsTests for platforms that support it

### PR DESCRIPTION
**Pull request by iamjasonp**
This set of tests should work for Debian and Ubuntu, as they by default have libcurl+OpenSSL installed

### CODE REVIEW

**Comment by roncain** [comment]
LGTM.

Incidentally, you should also be able to use XOR to remove bits from the OSID mask if it's easier to express.  Totally your stylistic choice.
```
[Issue(999, OS = OSID.AnyUnix ^ (OSID.AnyUbuntu | OSID.AnyDebian))]
```

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
Thanks for the comment @roncain 
Don't merge this yet btw - there's still some weirdness about the Peer CA certs that wasn't fixed by the last change I made to corefx. Investigating now

**Comment by iamjasonp** [comment]
> Incidentally, you should also be able to use XOR to remove bits from the OSID mask if it's easier to express. Totally your stylistic choice.

Personally I like the explicit nature of what to exclude as the convention - it means that we can easily grep for the tests that are excluded :smile:

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test innerloop Debian8.4, test outerloop Debian8.4

**Comment by iamjasonp** [comment]
@dotnet-bot test innerloop Debian8.4, test outerloop Debian8.4

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Debian8.4, test outerloop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test InnerLoop Ubuntu16.04, test OuterLoop Ubuntu16.04

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu16.04

**Comment by roncain** [comment]
LGTM.
I agree -- explicitly listing the OSes where it doesn't work seems better. It shows we tested them and know they don't work there.

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu16.04

**Pull request merged**
