### PR TITLE
Combine all test dependencies into one common project.json

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* This was done in CoreFx with PR #12345
* Although not as impactful as for CoreFx this will shorten the time it takes to sync.
* In addition, as a simplification improvement it makes a lot of sense.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@karajas when you made this change for CoreFx, was there any impact on Helix runs, do we need to update anything in any build definition or the pipe build project?

**Comment by karajas** [comment]
The major fallout was the failing of of non-core test runs (uwp, ilc, desktop).

**Comment by StephenBonikowsky** [comment]
We have ilc runs, what sort of failures did you have, what did you have to do to fix them?

**Comment by karajas** [comment]
The failures were in regards to not picking up the latest version of TestSuite (925-01) which you have. I think we currently also have some issues with the ILC runner still due to some other corefx changes, @MattGal do you have more context here?

**Comment by MattGal** [comment]
Currently ILC run success is blocked by changes to System.Console which cause it to throw exceptions if color APIs are used.  It does not log this nicely in runs unfortunately, but is easy to repro using the Helix repro tool.  

I need to get an issue created about this, will update this thread when I do.

**Comment by karajas** [comment]
But this should be non-blocking to the change I believe.

**Comment by MattGal** [comment]
Correct.  If I get some free time I'll just fix it up myself.

**Comment by StephenBonikowsky** [comment]
So the ilc runs will work but just get incorrectly reported?

**Pull request merged**
