### PR TITLE
Removing Bridge related code from build script.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* With recent infrastructure changes we no longer need the bridge to be started by the build script.
* At the same time PR dotnet/corefx#7894 adds setup and cleanup extension points to the build script.
* As soon as this is merged in corefx I will port it to wcf.

### CODE REVIEW

**Comment by zhenlan** [comment]
LGTM.

dotnet/corefx#7894 can take longer, but this change will stop starting bridge, so it's good to take anyway.

**Comment by iamjasonp** [comment]
Should this go into the infrastructure branch? Disabling outerloops from the master branch will break CI outerloops until the infrastructure branch merges into master. 

Changes LGTM subject to confirming where this change should go.

**Comment by iamjasonp** [comment]
Whoops. Just noticed that #1041 is merged already. Disregard :)

**Comment by iamjasonp** [comment]
@dotnet-bot Innerloop OSX Release

**Comment by iamjasonp** [comment]
@dotnet-bot test Innerloop OSX

**Comment by iamjasonp** [comment]
@dotnet-bot test Outerloop Windows_NT

**Comment by hongdai** [comment]
@dotnet-bot test Outerloop Windows_NT

**Pull request merged**
