### PR TITLE
[release/1.1.0] Move WCF to stable

### PR DESCRIPTION
**Pull request by ericstj**
This temporarily switches WCF to use a baseline package for versions
of CoreFx that have not yet been published.  This should be replaced
with the actual CoreFx build once its available.

/cc @StephenBonikowsky @zhenlan

### CODE REVIEW

**Comment by ericstj** [comment]
Once https://github.com/dotnet/corefx/pull/13097 is merged we should pick up that build for testing/baseline.  Without it this will fail the official build process that tests against packages (due to the missing CoreFx stable dependencies).

**Comment by StephenBonikowsky** [comment]
So we are just waiting for dotnet/corefx#13097 to be merged before we merge this PR?

**Comment by ericstj** [comment]
We need an official build with that change in it to complete, then we can ingest it, update this PR, then merge.

**Comment by ericstj** [comment]
This should be good to go now, pending testing.  I updated both CoreFx and CoreCLR to latest from 1.1.0 and undid my hack.

**Comment by ericstj** [comment]
Tests seem to be failing due to downgrading System.Net.Http.  /cc @bartonjs 

Stacks show
```
System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.\n (Exception from HRESULT: 0x8007007E)
```

However this DLL should still exist, even given the downgrade... investigating.

**Comment by ericstj** [comment]
Oh, I see what's happening.  The package transitioned from split to fat.  The runtime.json no longer has the links for old package (eg: runtime.native.System.Security.Cryptography -> runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography) so that's what caused them to get dropped.

This will happen on any standalone app that gets partially upgraded.

**Comment by ericstj** [comment]
I upgraded all the tests to fix this.

**Comment by StephenBonikowsky** [comment]
Looks good, just waiting for CI results.

**Comment by ericstj** [comment]
These look like more downgrades.  Tracking it down.

**Comment by ericstj** [comment]
These aren't actually downgrades, they're happening because I updated the common test projects.  You're using project-references between these common projects and other test projects, so their dependencies don't flow.  By upgrading the dependencies in the common projects and not explicitly calling those out in the other tests the tests get the old versions.

**Comment by ericstj** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Release

**Comment by ericstj** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by ericstj** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by ericstj** [comment]
@dotnet-bot test @dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by ericstj** [comment]
@mmitche any idea what's going on with the CI?

Looks like Ubuntu outerloop machines are having issues with restore and OSX runs aren't even starting

**Comment by ericstj** [comment]
I deleted one of the Ubuntu machines that was having issues, the other seems to be progressing now.

**Comment by mmitche** [comment]
@ericstj I'm seeing cases where wcf and corefx are hanging while runing tests (which is casuing a backup)

**Comment by ericstj** [comment]
I see.  Looks like this one will likely be green, once we can get it to run the OSX tests.

**Pull request merged**
