### PR TITLE
Update packages to rc3-23725

### PR DESCRIPTION
**Pull request by iamjasonp**
* Update package versions to rc3-23715
* Add imports for dnxcore to avoid a compat issue with xunit causing xunit.abstractions to not resolve in test projects 
* Add dir.props package version validation for TargetingPacks and add Microsoft.TargetingPack.Private.WinRT-1.0.0 to dependencies for System.Private.ServiceModel to pull in winmd files for netcore50
* Update buildtools to 1.0.25-prerelease-00154

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by iamjasonp** [comment]
Note: this does not yet build on Linux - trying to get to the bottom of this. Errors seen look like this:

```
n/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
  EXEC : error : System.Net.WebSockets.Client 4.0.0-rc3-23725 provides a compile-time reference assembly for System.Net.WebSockets.Client on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/jason/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
  EXEC : error : System.ObjectModel 4.0.0 provides a compile-time reference assembly for System.ObjectModel on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/jason/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
  EXEC : error : System.Reflection 4.0.0 provides a compile-time reference assembly for System.Reflection on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/jason/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
  EXEC : error : System.Runtime.InteropServices 4.0.0 provides a compile-time reference assembly for System.Runtime.InteropServices on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/jason/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
  EXEC : error : System.Security.Cryptography.X509Certificates 4.0.0-rc3-23725 provides a compile-time reference assembly for System.Security.Cryptography.X509Certificates on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/jason/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
  EXEC : error : System.Threading 4.0.0 provides a compile-time reference assembly for System.Threading on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/home/jason/git/wcf/src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj]
```

**Comment by iamjasonp** [comment]
This in theory should fix #619, #616, but verification is blocked becasue the build complains that the ubuntu runtime packages aren't published/found. Trying to figure out a way around this one, but stumped at the moment. 

@ericstj, might you be able to shed some light on this? 

For many of the packages the build is complaining about, I see unix runtime packages published to myget, but no ubuntu ones.

**Comment by iamjasonp** [comment]
In the runtime.json of System.Net.Primitives.4.0.11-rc3-23725.nupkg: 

```json
{
  "runtimes": {
    "win7": {
      "System.Net.Primitives": {
        "runtime.win7.System.Net.Primitives": "4.0.11-rc3-23725"
      }
    },
    "unix": {
      "System.Net.Primitives": {
        "runtime.unix.System.Net.Primitives": "4.0.11-rc3-23725"
      }
    }
  }
}
```

Maybe these runtime.json files need to be built with an "ubuntu" entry too?

**Comment by roncain** [comment]
I notice CoreFx has recently updated init-tools.cmd and init-tools.cmd.  I don't know if these will address what you are seeing.  I hate bundling mixed changes into one PR, but if it helps and you can make it an independent commit, we can selectively cherry pick for RC.

**Comment by ericstj** [comment]
@iamjasonp we don't build Ubuntu-specific libs.  The UNIX and/or Linux should apply to Ubuntu.  It looks like this project (System.Private.ServiceModel) is missing a reference to Microsoft.NETCore.Platforms.  That is the package that brings in the runtime ID graph that associates Ubuntu with UNIX.

All of these errors are NuGet's compat checks.  Those checks were temporarily relaxed in later builds of the CLI so it's possible an upgrade to CLI might give you some more time to fix up projects.

**Comment by iamjasonp** [comment]
@erijstj - odd. The only place where I see "Microsoft.NETCore.Platforms" referenced in a project.json is in test-runtimes (here and in corefx). 

What is a newer CLI version I can sync to? We're currently using the same as corefx, v1.0.0.000973

@roncain - the recent init-tools.sh changes don't seem to help us here - it's about using cURL instead of wget. I won't include the changes here to avoid your wrath :smiley:

**Comment by iamjasonp** [comment]
@ericstj - just tried to add Microsoft.NetCore.Platforms to System.Private.ServiceModel's project.json - the build output does not seem to have changed

**Comment by ericstj** [comment]
So I cloned your branch and ran restore and it works for me on a windows machine.  I then explicitly added the Ubuntu RID to the project.json that was failing in your log and it still works for me.  I do see the errors in the project.lock.json that the CLI is mentioning, but no errors from the tool when run on Windows.  @anurse does this have something to do with how you disabled the compat checks?

I did notice when run on windows that adding "Microsoft.NETCore.Platforms": "1.0.1-rc3-23725" did address many of the problems in the project.lock.json file... Of course it didn't address the TargetingPack errors; @weshaggard  needs to have a look at that and fix how we pull in the targeting pack.

Are you sure you are actually using the new version of the CLI when you are building on Unix?  It looks to me like you don't have @anurse's fix to disable the compat checks.

**Comment by iamjasonp** [comment]
Oooh, this may have been the work of 7c04308, when building on Linux... i.e., defaulting to a Windows_NT_Debug build. When I specified a build to mono: 

`mono ~/git/wcf/packages/Microsoft.Build.Mono.Debug.14.1.0.0-prerelease/lib/MSBuild.exe /t:Rebuild System.Private.ServiceModel.csproj /v:d /fl /p:Configuration=Linux_Debug`

with an explicit configuration, it seems to have changed the results and I got a clean build. I just updated this PR adding "Microsoft.NETCore.Platforms" to see if the CI machine reports a good build.

**Comment by iamjasonp** [comment]
@dotnet-bot test Linux Debug Build and Test please

**Comment by iamjasonp** [comment]
@dotet-bot test this please

**Comment by iamjasonp** [comment]
@dotnet-bot test this please

**Comment by iamjasonp** [comment]
The Jenkins pull request builder doesn't seem to be receiving commands from this PR. On @mmitche's advice, closing and reopening this PR to give it a kickstart.

**Comment by roncain** [comment]
LGTM

**Comment by roncain** [comment]
Merging now because this allows further debugging.

**Pull request merged**
