### PR TITLE
Porting PR1272 to update package versions to rc3-24206

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* This change was also made to the WCF/Master branch via PR#1272

* Cherry picking that commit to the release/1.0.0 branch was resulting in all the changes being conflicts and requiring manual resolution.

* I could not figure out how to make them merge, therefore it was quicker to make the same change directly here.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Comment by roncain** [comment]
LGTM, subject to CI jobs passing.
I pulled the patch and manually verified it built and passed all inner and outerloops.

**Comment by zhenlan** [comment]
cc: @joshfree

**Comment by StephenBonikowsky** [comment]
The three test cases failing in the Windows outerloop runs first started failing with PR #1264 In that case @roncain made the following comment...

> FYI -- I've manually run OuterLoops same-machine-self-hosted as well as cross-machine-self-hosted and have not seen any errors. I believe the CI OuterLoop failures for anything other than self-host reflect only our own infrastructure issues, not anything to do with this PR.

I believe that is the case here as these same tests pass on the Outerloop "Selfhost" Windows runs.

**Comment by joshfree** [comment]
Thanks for making this update!

**Pull request merged**
