### PR TITLE
Fix OS Detect logic

### PR DESCRIPTION
**Pull request by hongdai**
* Need to detect from OS description

### CODE REVIEW

**Comment by hongdai** [comment]
@dotnet-bot test Outerloop rhel7.2 please.

**Comment by hongdai** [comment]
@dotnet-bot test Outerloop rhel7.2 please

**Comment by hongdai** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug please.

**Comment by StephenBonikowsky** [comment]
LGTM

**Pull request merged**
