### PR TITLE
Rename test files with release version

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
In the renaming I did not include the scenario test file for infrastructure as I don't think this applies.

I moved PeerTrust tests into new files but after an initial pass I didn't find other tests that have had product fixes since 4.1.0 release for Windows, only *nix.

### CODE REVIEW

**Comment by iamjasonp** [comment]
LGTM, ran locally, looks good

**Comment by roncain** [comment]
When I run "N on K using RTM packages" with this PR using our prior instructions, I get failures due to missing API's.  I think we need to check with @shmao on the proper way to test this againt "N on K using RTM packages" now.  It might be that we need to update the CLRTestContractReferences in the ToF wrapper projects to later versions now.

One big one is the absence of X509Certificate2.Thumbprint in RTM.  Fortunately, recent infrastructure changes tolerate the MissingMethodException in the ConditionalFact detectors and just cause the cert ConditionalFacts to all return false.  But there are some tests that explicitly reference Thumbprint and fail -- so those might need to be reverted to "pre-release" naming, depending what we discover about CLRTestContractReference

It might be that the PR is fine and we only need to fix the ToF side, but it will take some experimentation.

Examples of missing-API failures:
```
  Running Test: HttpsTests.CrossBinding_Soap11_EchoString
  Caught Unexpected exception:System.Exception: Method 'OSPlatform.get_Windows()' was not included in compilation, but was referenced in ConditionalTestDetectors.IsWindows(). There may have been a missing assembly.
     at Infrastructure.Common.ConditionalTestDetectors.IsWindows()
     at System.Func$1.InvokeOpenStaticThunk()
     at System.Func$1.Invoke()
     at Infrastructure.Common.ConditionalWcfTest.GetConditionValue(String conditionName, Func$1 detectFunc, Boolean result) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Common\Infrastructure\ConditionalWcfTest.cs:line 65
     at HttpsTests.CrossBinding_Soap11_EchoString(Boolean root_Certificate_Installed) in e:\oss\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Https\HttpsTests.4.1.0.cs:line 30
     at EntryPointMain.<>c.
b__0_7() in E:\ProjectK\src\QA\ToF\PN\x86\rel\IL\FX\Conformance\System.Private.ServiceModel\4.0.0.0\WcfOpen\Scenarios\Security\TransportSecurity\Security.TransportSecurity.Tests.main.cs:line 20
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Exception ex) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------
```

```
  --------------------------------
  Running Test: HttpsTests.ClientCertificate_EchoString
  Caught Unexpected exception:System.Exception: Method 'BasicHttpsBinding..ctor(BasicHttpsSecurityMode)' was not included in compilation, but was referenced in HttpsTests.ClientCertificate_EchoString(). There may have been a missing assembly.
     at EntryPointMain.<>c.
b__0_12()
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Exception ex) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------
```

```
Running Test: Http_ClientCredentialTypeTests.DigestAuthentication_Echo_RoundTrips_String_No_Domain
  Caught Unexpected exception:System.ServiceModel.CommunicationException: net_http_client_execution_error ---> System.Net.Http.HttpRequestException: net_http_client_execution_error ---> System.NotSupportedException: NotSupported_CloningNotSupported, GetInputStreamAt
     at System.IO.NetFxToWinRtStreamAdapter.ThrowCloningNotSuported(String methodName) in f:\dd\ndp\fxcore\src\System.Runtime.WindowsRuntime\System\IO\NetFxToWinRtStreamAdapter.cs:line 442
     at System.IO.NetFxToWinRtStreamAdapter.GetInputStreamAt(UInt64 position) in f:\dd\ndp\fxcore\src\System.Runtime.WindowsRuntime\System\IO\NetFxToWinRtStreamAdapter.cs:line 455
     at McgInterop.ReverseComSharedStubs.Func_ulong__TResult__(Object __this, UInt64 unsafe_position, Void** unsafe_stream__retval, IntPtr __methodPtr, Int32 CS$1$0000) in c:\Users\roncain\AppData\Local\Temp\Ilc333147997\Security.TransportSecurity.Tests.McgInterop\SharedStubs.g.cs:line 5503

```

```
  Running Test: Tcp_ClientCredentialTypeCertificateCanonicalNameTests.Certificate_With_CanonicalName_Localhost_Address_EchoString
  Caught Unexpected exception:System.Exception: Method 'ClientCredentials.get_ServiceCertificate()' was not included in compilation, but was referenced in Tcp_ClientCredentialTypeCertificateCanonicalNameTests.Certificate_With_CanonicalName_Localhost_Address_EchoString(). There may have been a missing assembly.
     at EntryPointMain.<>c.
b__0_26()
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Exception ex) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------
```

```
  --------------------------------
  Running Test: Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString
  Caught Unexpected exception:System.Exception: Method 'X509Certificate2.get_Thumbprint()' was not included in compilation, but was referenced in Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString(). There may have been a missing assembly.
     at EntryPointMain.<>c.
b__0_29()
     at System.Action.Invoke()
     at CoreFXTestLibrary.Internal.Runner.RunTestMethod$catch$0() in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 170
     at CoreFXTestLibrary.Internal.Runner.RunTest($TestInfo t, Exception ex) in E:\ProjectK\src\QA\ToF\Tests\FX\Conformance\Common\Xunit\Internal\Runner.cs:line 95
  ---- Test FAILED ---------------
```

**Comment by StephenBonikowsky** [comment]
Hi Ron, sorry I should have mentioned in my PR that I still had to do the run you just did in order to find additional tests that need to be moved out of the newly renamed files into “current” pre-release test files.

After discussing this with Zhenlan we don’t care about RTM, just most recently released version. So yes we will probably have to make a few changes, I will follow-up with Shin. I also expected a few tests would need to be moved to the “current” pre-release test files.

I got side-tracked yesterday by the TFS build break and didn’t get to this.

-Stephen

**Comment by roncain** [comment]
Just checking @StephenBonikowsky -- renaming the PeerTrust tests back to their original names -- does that make them exactly as they were prior to this PR?  I've been working on those tests this week and will need to merge after you checkin.

**Comment by StephenBonikowsky** [comment]
I'm not changing the names of any tests, or is that what you are doing? This PR makes no change in terms of the namespace and name of any tests.

I've been running the N-on-K starting yesterday, it is more complicated than just running against latest packages, @shmao put something together for me yesterday but I still have very bad results, need to work with him on this today.

**Comment by roncain** [comment]
@StephenBonikowsky  -- I was just verifying that after you merge, the tests will still be in the files where they are now (pre-merge), but the file itself will be different since the other tests have been moved.  No biggie -- I've been adding new PeerTrust tests and renaming older ones.  I'll just merge carefully.

BTW, N-on-K seems broken right now, so I don't think either of us can verify it works 😦

**Comment by StephenBonikowsky** [comment]
Well Shin and I are trying, we are using published builds which should be ok.

**Comment by StephenBonikowsky** [comment]
I got the N on K run working using ILC version 24308.00 from a few days ago, this was good enough to validate what has changed since the netcore50 release.
Updated this PR with those changes via a new commit.

**Comment by StephenBonikowsky** [comment]
Missed one file, amended the previous commit.

**Comment by StephenBonikowsky** [comment]
Updated once more, it turns out there is a product bug in netnative being hit by the MessageInterceptor test, I will open an Issue for it but this test needs to remain in a pre-release test file.

**Comment by StephenBonikowsky** [comment]
Opened Issue #1374 Did not add it as an active issue to the test case yet as I would like an independent confirmation.

**Comment by iamjasonp** [comment]
LGTM subject to you having run N on K. Thanks for dealing with this :)

**Comment by roncain** [comment]
@StephenBonikowsky -- I can't repro the issue reported for #1374 using normal N-on-K.  But I would predict exactly the failure reported in that issue if it were tested using latest WCF shipped packages.

**Pull request merged**
