### PR TITLE
Add condition to proj ref of S.P.SM

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* This project reference is causing strange build behavior in the VSO build pipeline. Since in that environment it is supposed to build test using the actual packages anyway these project references should not be used.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
Adding @ericstj  and @chcosta

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Comment by StephenBonikowsky** [comment]
I tested this in a private branch on VSO and it worked.

**Comment by iamjasonp** [comment]
LGTM, given that you've tested this in VSO.

**Comment by ericstj** [comment]
I think you should have a look at the way we're doing test > product references in CoreFx now using pkgprojs.  Also if you already have a targets file defining the path to the S.P.SM project, why not avoid a ton of duplication and put the item in the targets file as well, conditioned of course.  Not needed for this PR, but something to condsider.

**Pull request merged**
