### PR TITLE
Fix to the WCF event source that will alleviate the problems with ToF CHK tests

### PR DESCRIPTION
**Pull request by dmetzgar**
This fixed the issue in my testing and doesn't require changes to EventSource or renumbering the event ids.

### CODE REVIEW

**Comment by dmetzgar** [comment]
Fixes #313

**Comment by roncain** [comment]
Questions only @dmetzgar -- what is the affect of not setting this property in the attribute?  Does it affect how the event appears to tooling?  It passes innerloop and outerloop tests on my machine, but I'd like to do a full CHK build in TFS to see how it behaves in ToF, but that will take a couple hours.  Were you able to try this fix in a CHK build against ToF already?

**Comment by dmetzgar** [comment]
@roncain I used my repro of the issue here: https://github.com/dmetzgar/eventsourcetest
The original manifest takes **2.88 days** to complete. With this change it takes **0.02 secs**. Opcode.Info is the default opcode for an event. But explicitly setting it appears to cause problems with the current EventSource code. That code still needs to be fixed. At least with this PR we do not have to revisit this later from WCF side.

**Comment by dmetzgar** [comment]
@dotnet-bot retest this please

**Comment by roncain** [comment]
LGTM.  I'll confirm with a CHK ToF run tomorrow, but recommend you go ahead and merge now.

**Pull request merged**
