### PR TITLE
Update project.json dependencies to rc2-23628.

### LINKED ISSUE #656: Update project.json dependencies to rc2-23628
#632 requires this.

### PR DESCRIPTION
**Pull request by shmao**
1. Updated project.json files.
2. Changed to use NegotiateStream.AuthenticateAsServerAsync() instead of  NegotiateStream.AuthenticateAsServer() as the later one got removed.

Fixes #656.

### CODE REVIEW

**Comment by shmao** [comment]
@dotnet-bot test outerloop please

**Comment by mconnew** [comment]
@dotnet-bot test outerloop please

**Comment by mconnew** [comment]
It looks like we have a problem with the CI machine. I've done a buddy build and ran the outerloop tests and everything is passing.
LGTM

**Comment by shmao** [comment]
@dotnet-bot test outerloop please

**Comment by shmao** [comment]
@mconnew Thanks for buddy build the PR. Can I merge the PR in this case?

**Comment by mconnew** [comment]
Yes, go ahead and merge

**Pull request merged**
