### PR TITLE
Bump versions across WCF and move to beta

### PR DESCRIPTION
**Pull request by ericstj**
Now that we have stable packages for our current versions we need to
bump the 3rd portion (bugfix) to represent code-changes without API
additions.

This also updates product code to build against stable dependencies.

/cc @weshaggard @StephenBonikowsky @roncain @zhenlan

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.0

**Comment by StephenBonikowsky** [comment]
I'm not sure why we are getting this one test failure only on Ubuntu 14 and only on the release flavor.

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.01Leave a comment

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Comment by StephenBonikowsky** [comment]
@ericstj Re-runs of the Ubuntu outerloops still fails but now I don't see the single test case failure I saw before, instead I get the following error in the console output...

14:18:02 Restoring BuildTools version 1.0.25-prerelease-00507-05...
14:19:54 ERROR: Could not restore build tools correctly. See '/mnt/j/workspace/dotnet_wcf/master/outerloop_ubuntu14.04_release_prtest/init-tools.log' for more details.

Not sure what to make of this.

**Comment by ericstj** [comment]
That package is available here; https://dotnet.myget.org/feed/dotnet-buildtools/package/nuget/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00507-05.  Would need to see the contents of init-tools.log to know more.  It's possible that machine has some bad state that's causing init-tools to fail.

**Comment by weshaggard** [comment]
LGTM

**Comment by ericstj** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Release

**Comment by roncain** [comment]
LGTM.
@StephenBonikowsky -- any comments before we merge this iteration?
I believe the one test failure is unrelated to this PR itself.

**Comment by StephenBonikowsky** [comment]
The same test case fails repeatedly and only with this PR, only Ubuntu and only on Release. It feels like some package has introduced a bug but we would need to be able to reproduce this outside of the CI environment in order to find the cause.

Going to merge and then look for this failure in our subsequent runs.

**Pull request merged**
