### PR TITLE
Enable previously-skipped tests in Infrastructure, http

### PR DESCRIPTION
**Pull request by iamjasonp**

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by roncain** [comment]
LGTM, subject to CI Passing.

**Comment by iamjasonp** [comment]
I'm tracing down an issue right now where the rootCertificate is not being found by the X509Store.Find() method... so holding off on merging until I know what's going on

**Comment by iamjasonp** [comment]
Found it - it's in our implementation of the PlatformSpecificRootStoreLocation, so I need to go and figure out how best to change that method

**Comment by iamjasonp** [comment]
I'll let #1475 re-enable Root_Certificate_Correctly_Installed. The two other tests being re-enabled should pass though

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Debian7.1

**Comment by iamjasonp** [comment]
@dotnet-bot test OuterLoop Debian8.4

**Comment by iamjasonp** [comment]
Ok, hopefully with the latest changes to certificates in corefx, these will _finally_ pass :smile:

**Comment by roncain** [comment]
LGTM.
Feel free to merge anytime.  I'll merge #1475 as soon as I get a thumbs up (or feel free to merge it yourself).

**Comment by iamjasonp** [comment]
Don't merge this PR please... there is something with the client cert case that is not right. I'm still investigating

**Comment by iamjasonp** [comment]
dotnet/corefx#12214 blocking this issue

**Comment by iamjasonp** [comment]
#1475, #1575 have done the work of this PR - closing

**Pull request closed without merging**
