### PR TITLE
Build against ns20

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
Recreated Wes' changes first from PR #1768 
Updated test .builds files and test projects and the test-runtime common project.json

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@weshaggard 
I re-created your changes and make a few on top of that to try and fix the unit tests.

The current state is that the unit test projects build fine but they contain project references to common projects and those are failing because it looks like they are not pulling in the test-runtime project.json.

This can be reproduced by msbuilding any of the unit test projects after first commenting out any common project references, the only build errors you will get are related to needing those common projects.

If you msbuild any of the test common projects you will get errors for common types such as system.string and system.object.

I have tried a lot of things but cannot figure out what is preventing the test common projects from using the test-runtime project.json to resolve its dependencies.

WCF Unit test projects...
https://github.com/dotnet/wcf/tree/master/src/System.ServiceModel.Duplex/tests
https://github.com/dotnet/wcf/tree/master/src/System.ServiceModel.Http/tests
https://github.com/dotnet/wcf/tree/master/src/System.ServiceModel.NetTcp/tests
https://github.com/dotnet/wcf/tree/master/src/System.ServiceModel.Primitives/tests
https://github.com/dotnet/wcf/tree/master/src/System.ServiceModel.Security/tests

WCF Common test projects...
https://github.com/dotnet/wcf/tree/master/src/System.Private.ServiceModel/tests/Common

test-runtime project.json
https://github.com/dotnet/wcf/blob/master/src/Common/test-runtime/project.json

**Comment by StephenBonikowsky** [comment]
@weshaggard when you have time could you take a look. I think all we need to get us building and running against 2.0 is figuring out how to build our test common projects using the test-runtime/project.json

**Comment by weshaggard** [comment]
@StephenBonikowsky Yes I will try to take a closer look today.

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
I started playing with this and I have more of it working but I'm currently stuck with needing a BuildTools update to get an updated nuget version. I'm going to look at that over the next few days.

**Comment by StephenBonikowsky** [comment]
@weshaggard should we close this PR now or is it still needed?

**Comment by weshaggard** [comment]
Feel free to close and replace as needed. I'm leaving this up to you an and @MattGal

**Comment by MattGal** [comment]
I'll be starting on this shortly, I plan to make my own PR so this can be closed as I'll just get these changes for Wes' fork.

**Comment by StephenBonikowsky** [comment]
Ok, cool.

**Pull request closed without merging**
