### PR TITLE
Remove latest dependences build from netci.groovy

### PR DESCRIPTION
**Pull request by iamjasonp**
... but for now, keep the command around as a comment in case we need it for
the near future. We can remove the comment later should we find that we haven't
needed it for a long time

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
@hongdai - any concerns with removing this?

**Comment by zhenlan** [comment]
Given the packing change due to netstandard support, we will always depend on latest packages and let netstandard decide which part of assets of a package should be used. This latest dependency build should not be needed anymore.

This PR LGTM.

**Comment by hongdai** [comment]
LGTM.

**Pull request merged**
