### PR TITLE
Bump primitives

### PR DESCRIPTION
**Pull request by ericstj**
Make a couple changes to bring WCF up on latest buildtools and bump version of primitives.

/cc @StephenBonikowsky

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by ericstj** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Release

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by StephenBonikowsky** [comment]
LGTM

**Pull request merged**
