### PR TITLE
Add reference assembly projects for significant past contract versions

### PR DESCRIPTION
**Pull request by ericstj**
This change adds projects to pull the reference assemblies from past packages for any significant contract revision. Significant here means a version with different surface area that is supported on a different set of platforms. EG. System.Runtime 4.0.0 supported desktop 4.5, System.Runtime 4.0.10 supported desktop 4.5.1, etc.

These are needed for generations support in our nuget packages.

This is the WCF portion of https://github.com/dotnet/corefx/pull/3589.

### CODE REVIEW

**Comment by iamjasonp** [comment]
LGTM

**Comment by roncain** [comment]
LGTM.  I pulled this PR and ran all InnerLoop and OuterLoop tests successfully.
@ericstj , @mconnew and @iamjasonp -- this version of the build tools is different than the one in PR https://github.com/dotnet/wcf/pull/382 (it uses version 97) that Matt is preparing to get into beta8 asap.
Any thoughts on which one should go first and which should merge?  We will need to ask permission to move this change into the locked-down beta8 TFS enlistment, so we need to understand the risks of a combined PR.

**Comment by ericstj** [comment]
Either one is fine.  This PR can wait, it's not going in beta8 though if it did I wouldn't be too worried since nothing in the rel branch will be consuming these new projects.  Since @mconnew's PR also has source fixes I'd just take that one.  We can let this PR wait until that's out of the way and I'll rebase.

**Comment by roncain** [comment]
@ericstj -- thanks for the advice.  Matt has merged his PR bringing us to version 97 of build tools.  When it's convenient, would you mind rebasing and updating your PR.  I'll test it against our OuterLoops as well as against NET Native.

**Comment by ericstj** [comment]
@roncain this should be ready to merge now.

**Comment by roncain** [comment]
Thanks @ericstj .  I'm trying to build this PR in TFS and encountering a build error I'm debugging.  If I don't see an answer, I'll try a full scorch and rebuild.

       "E:\ProjectK\src\NDP\FxCore\dirs.proj" (clean target) (1) ->
       "E:\ProjectK\src\NDP\FxCore\src\dirs.proj" (Clean target) (2) ->
       "E:\ProjectK\src\NDP\FxCore\src\libs.msbuild" (Clean target) (356) ->
       "E:\ProjectK\src\NDP\FxCore\src\System.ServiceModel.Primitives\System.ServiceModel.Primitives.NETNative.csproj" (Clean target) (575) ->
       "E:\ProjectK\src\NDP\FxCore\src\System.Private.ServiceModel\System.Private.ServiceModel.NETNative.csproj" (Clean target) (510:4) ->
         E:\ProjectK\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104\lib\packageresolve.targets(54,5): error MSB4184: The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long. [E:\ProjectK\src\NDP\FxCore\src\System.Private.ServiceModel\System.Private.ServiceModel.NETNative.csproj]

**Comment by ericstj** [comment]
Let me have a look.  Seems like the TFM/TPM settings for System.Private.ServiceModel.NETNative.csproj are inconsistent.

**Pull request merged**
