### PR TITLE
Moving test case into correct location.

### LINKED ISSUE #1298: Move test case out of 4.0.0 file.
Test case "DuplexChannelShapeTests.IRequestChannel_Https_NetHttpsBinding" was incorrectly added to  ...Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

It needs to be moved to "...System.Private.ServiceModel\tests\Scenarios\Client\ChannelLayer\DuplexChannelShapeTests.cs"

The test uses a new API that was added as mentioned in #507 so it cannot work on 4.0.0.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* See Issue #1298 for details.
* Fixes #1298

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test all outerloop please

**Comment by iamjasonp** [comment]
@StephenBonikowsky - you mentioned that a test needed to be "moved" but I see only an addition and not a corresponding removal of a test from the 4.0.0.cs file. 

I expected that there'd be a deletion from DuplexChannelShapeTests.4.0.0.cs somewhere as described in #1298?

**Comment by StephenBonikowsky** [comment]
Umm...yeah 💩

**Comment by iamjasonp** [comment]
Heh :) LGTM now

**Comment by zhenlan** [comment]
I didn't do line-by-line comparison, but suppose they are the cut-and-paste. LGTM.

**Pull request merged**
