### PR TITLE
Fix certificate generation and installation issues

### PR DESCRIPTION
**Pull request by iamjasonp**

### CODE REVIEW

**Comment by iamjasonp** [comment]
See comments in individual commits. Note that we can't reliably test against this until committed due to this touching the certificate generation logic - which would necessitate touching the servers as well

**Comment by hongdai** [comment]
@iamjasonp Thanks for getting to the bottom of this and figured out a solution! Ubuntu CI has a problem now. LGTM.

**Comment by iamjasonp** [comment]
@dotnet-bot test Outerloop Ubuntu14.04 please

**Comment by iamjasonp** [comment]
Yeah, I requested the machines be rebuilt; hopefully this makes the Ubuntu outerloops pass. 

I'm still running a couple of tests on my end to see what we get. I'm getting some new errors that I want to take a look through

**Comment by iamjasonp** [comment]
Merging - I will be touching the certificate generation on the necessary servers shortly

**Pull request merged**
