### PR TITLE
Add package descriptions for Nuget packages

### PR DESCRIPTION
**Pull request by kant2002**
See https://twitter.com/davidfowl/status/1547936507821928455 for context 😄

### CODE REVIEW

**Comment by HongGit** [comment]
@samsp-msft can you please review this?

**Comment by imcarolwang** [comment]
Need a rebase to pass the checks.

**Comment by kant2002** [comment]
@imcarolwang I do rebase

**Comment by HongGit** [comment]
@kant2002 this PR is outdated, the *.Facade.csproj are removed now, could you please update this PR?  We would like to incorporate your change in the upcoming release.  

Thank you so much for your contribution!

**Comment by kant2002** [comment]
@HongGit please take a look. I did not set description for `System.ServiceModel.NetFramingBase` because I do not sure what's going on here.

**Comment by HongGit** [comment]
@kant2002 Thank you for the update!  Please refer to [Readme.me](https://github.com/dotnet/wcf#readme), for a complete list of package description, which includes` System.ServiceModel.NetFramingBase` and others.  Can you please review and make sure that your update aligns with [Readme.me](https://github.com/dotnet/wcf#readme)?

Thanks again for your quick turnaround!

**Comment by kant2002** [comment]
@HongGit can you take a look at descriptions for `System.ServiceModel.Federation` and `System.Web.Services.Description`. I do not sure, but I think descriptions in my PR slightly better then very short on you have in README. What do you think?

**Comment by HongGit** [comment]
@kant2002 LGTM.  

Thanks for your contribution!

**Pull request merged**
