### PR TITLE
Fix bug where async write was reporting completion before the Flush completed

### PR DESCRIPTION
**Pull request by mconnew**
Here is this sequence of events when the data is supposed to be sent immediately.  
* _socket.WriteAsync is called and returns a task (t1)
* t1.ContinueWith is called on this task where the delegate calls FlushAsync. ContinueWith returns a task t2.
* If t2 is Completed immediately, return AsyncCompletionResult.Completed

The problem is the FlushWriteImmediate method was an async void method so we weren't waiting on the flush completing and t1.ContinueWith would complete immediately which caused us to report the Write had completed. Another Write would then be called which would cause the new data to be appended to the write buffer which hadn't been cleared yet from the previous Flush. FlushAsync would then be called again and the entire buffer including the data from the first Write call would get sent. This had the effect of two consecutive immediate write calls in quick succession would cause the data from the first write to be sent on the socket twice.

### CODE REVIEW

**Comment by roncain** [comment]
Are there any specific issue numbers we can include and close with this checkin?

**Comment by mconnew** [comment]
I think I have at least one bug assigned to me. I'll find the correct bug number and reference it.

**Comment by roncain** [comment]
LGTM.
If there is a test currently disabled due to this issue, it would be great to reactivate it with this PR.

**Comment by mconnew** [comment]
Fixes #524 
Fixes #521 
Fixes #587 
Fixes #520 
This also will cause the correct exception to be thrown on Net Native as mentioned in issue #624

**Pull request merged**
