### PR TITLE
Adding PS script needed to publish packages via VSO pipeline.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* File is UpdatePublishedVersions.ps1 and it should have no diffs to the version in corefx.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test this please

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Windows_NT

**Comment by iamjasonp** [comment]
LGTM

**Pull request merged**
