### PR TITLE
Fix test failure on TOF

### PR DESCRIPTION
**Pull request by hongdai**
# TOF does not support some of the XUnit functionalities. Thus
I need to make the change to only use what it supports.

### CODE REVIEW

**Comment by iamjasonp** [comment]
LGTM.

**Comment by iamjasonp** [comment]
NIT: Not really sure what the # at the beginning of your commit message is for, but it makes it look super  funky when viewing this commit using any kind of UI :)

**Comment by hongdai** [comment]
@dotnet-bot , test outerloop please.

**Comment by hongdai** [comment]
@dotnet-bot test outerloop please

**Pull request merged**
