### PR TITLE
Update netci.groovy for new branches for outerloop

### PR DESCRIPTION
**Pull request by iamjasonp**
* release/1.1.0
* ws-trust

### CODE REVIEW

**Comment by iamjasonp** [comment]
**WARNING: this is for the ws-trust branch.**
Merge this only after the repos have been created on wcfcoresrv2

**Comment by zhenlan** [comment]
LGTM

Repos are being created in progress. I will merge when that is done.

**Comment by roncain** [comment]
LGTM.
We will wait to merge till after other necessary manual steps have been taken to create the new branch and increase the number of repros on the server.

**Comment by zhenlan** [comment]
Repo creation has done. Merging...

**Pull request merged**
