### PR TITLE
Mark client certs installed by BridgeClient as PersistKeySet

### LINKED ISSUE #495: TcpClientCredentialType_Certificate_EchoString test fails on some machines
Beginning with recent changes to BridgeClientCertificateManager, this test has begun failing consistently on certain machines, but not on others.  It fails consistently on @roncain's machines as well as CI OuterLoop.

                     Starting:    Security.TransportSecurity.Tests (TaskId:554)
                        Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString [FAIL] (TaskId:554)
                           System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized (TaskId:554)
                           Stack Trace: (TaskId:554)
                                 at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc) (TaskId:554)
                                 at System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential secureCredential) (TaskId:554)
                                 at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint) (TaskId:554)
                                 at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output) (TaskId:554)
                                 at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count) (TaskId:554)
                                 at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) (TaskId:554)
                                 at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest) (TaskId:554)
                                 at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) (TaskId:554)
                                 at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) (TaskId:554)
                                 at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\SslStreamSecurityUpgradeProvider.cs(618,0): at System.ServiceModel.Channels.SslStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty& remoteSecurity) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\StreamSecurityUpgradeInitiatorBase.cs(97,0): at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgrade(Stream stream) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(610,0): at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgrade(StreamUpgradeInitiator upgradeInitiator, IConnection& connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeoutHelper& timeoutHelper) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(285,0): at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<SendPreambleAsync>d__10.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ConnectionPoolHelper.cs(113,0): at System.ServiceModel.Channels.ConnectionPoolHelper.<EstablishConnectionAsync>d__15.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\FramingChannels.cs(368,0): at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.<OnOpenAsync>d__14.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(348,0): at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__71.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(1351,0): at System.ServiceModel.Channels.ServiceChannel.<OnOpenAsync>d__149.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(348,0): at System.ServiceModel.Channels.CommunicationObject.<System-ServiceModel-IAsyncCommunicationObject-OpenAsync>d__71.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(323,0): at System.ServiceModel.Channels.CommunicationObject.<OpenAsyncInternal>d__70.MoveNext() (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) (TaskId:554)
                                 at System.Runtime.CompilerServices.TaskAwaiter.GetResult() (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\Internals\System\Runtime\TaskHelpers.cs(184,0): at System.Runtime.TaskHelpers.WaitForCompletion(Task task) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\CommunicationObject.cs(317,0): at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(1976,0): at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(2043,0): at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(502,0): at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(747,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannel.cs(722,0): at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(371,0): at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\src\System\ServiceModel\Channels\ServiceChannelProxy.cs(139,0): at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) (TaskId:554)
                              --- End of stack trace from previous location where exception was thrown --- (TaskId:554)
                                 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() (TaskId:554)
                                 at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args) (TaskId:554)
                                 at generatedProxy_1.Echo(String ) (TaskId:554)
                              c:\OSS\wcf\src\System.Private.ServiceModel\tests\Scenarios\Security\TransportSecurity\Tcp\ClientCredentialTypeTests.cs(189,0): at Tcp_ClientCredentialTypeTests.TcpClientCredentialType_Certificate_EchoString() (TaskId:554)
                     Finished:    Security.TransportSecurity.Tests (TaskId:554)
                      (TaskId:554)
                     === TEST EXECUTION SUMMARY === (TaskId:554)
                        Security.TransportSecurity.Tests  Total: 14, Errors: 0, Failed: 1, Skipped: 0, Time: 2.894s (TaskId:554)

### PR DESCRIPTION
**Pull request by iamjasonp**
Mark all installed certificates as PersistKeySet; this seems to be a difference when
importing to the CurrentUser certificate store vs. the LocalMachine store in
Windows. This caused issues when attemtping to use the certificates in tests and
sems to avert the issue of the tcp tests running into the following excception:

```
System.ComponentModel.Win32Exception :
The credentials supplied to the package were not recognized
```

Fixes #495 (hopefully)

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please 

PR OuterLoop test builds are passing :smile: 
Running again, let's see if it's consistent.

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by iamjasonp** [comment]
@dotnet-bot test outerloop please

**Comment by roncain** [comment]
Passed OuterLoop for me.  Currently testing on Linux where cert tests are already known to fail, but I want to see if they now behave differently.

**Comment by iamjasonp** [comment]
Woohoo! I'll merge now so I can see OuterLoops pass cleanly for once :)

**Pull request merged**
