### PR TITLE
Updating to latest build tools version.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* Needed to fix VSO issues.

### CODE REVIEW

**Comment by roncain** [comment]
LGTM, subject only to CI tests passing

**Comment by iamjasonp** [comment]
Code LGTM, let's work to make these pass. 
Outerloops failures look transient (I think there's another work item for reducing flakiness there).

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop CentOS7.1

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop OSX

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Pull request merged**
