### PR TITLE
Update badges to use the new jobs

### PR DESCRIPTION
**Pull request by mmitche**
Code coverage and outerloop

### CODE REVIEW

**Comment by mmitche** [comment]
test code coverage please

**Comment by mmitche** [comment]
@dotnet-bot test code coverage please

**Comment by mmitche** [comment]
@dotnet-bot test outerloop please

**Comment by mmitche** [comment]
@roncain Check it out.  I think I fixed the Linux test issue btw.

**Comment by mmitche** [comment]
@roncain Right now I have the Linux builds disabled for PR just till I verify that it's working properly, but I'll enable them again tomorrow morning.

**Comment by iamjasonp** [comment]
Sweeet. LGTM

**Pull request merged**
