### PR TITLE
Enable Test EchoComositeType_XmlSerializerFormat_Soap

### LINKED ISSUE #1884: EchoComositeType_XmlSerializerFormat_Soap Failed
Test `EchoComositeType_XmlSerializerFormat_Soap` failed due to a bug in serialization. The bug would be fixed by dotnet/corefx#19258. We would need to update the dependencies to take the fix.

### PR DESCRIPTION
**Pull request by shmao**
Fix #1884

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop CentOS7.1

**Comment by StephenBonikowsky** [comment]
@dotnet-bot test outerloop Ubuntu14.04

**Comment by shmao** [comment]
@dotnet-bot test outerloop CentOS7.1
@dotnet-bot test outerloop Ubuntu14.04
@dotnet-bot test OuterLoop OSX10.12 Debug

**Comment by StephenBonikowsky** [comment]
The OSX failure is due to the SetupValidationTests.Client_Certificate_Correctly_Installed failure which has been flaky and is under investigation. Don't block on this test failure on any of the CI runs.

**Comment by shmao** [comment]
The tests failed on CentOS and Ubuntu due to `SetupValidationTests.Client_Certificate_Correctly_Installed`, which is flaky and under investigation. I'm merging the PR.

**Pull request merged**
