### PR TITLE
Change netci.groovy to pass ServiceUri in outerloops

### PR DESCRIPTION
**Pull request by iamjasonp**

### CODE REVIEW

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
@dotnet-bot test ci please

**Comment by iamjasonp** [comment]
Queues spot checked and the Windows outerloop queues have been checked to ensure they pass correctly. @roncain, @hongdai, assuming this receives an LGTM, merge at will if it will unblock test infrastructure work.

**Comment by hongdai** [comment]
@dotnet bot test Outerloop Windows_NT Debug Build and Test test Ubuntu14.04 Release Build and Test

**Comment by hongdai** [comment]
@dotnet bot test Outerloop Ubuntu14.04 Release Build and Test

**Comment by hongdai** [comment]
@dotnet bot test Outerloop Linux Release Build and Test

**Comment by iamjasonp** [comment]
@hongdai - testing outerloops here wouldn't matter here, because we're modifying the queue :) the queue will _not_ run with the new changes until merged

**Comment by iamjasonp** [comment]
Merging, to unblock infrastructure work

**Comment by zhenlan** [comment]
LGTM, post merge.

**Pull request merged**
