### PR TITLE
Fix type-o in the NetTcp.builds file

### PR DESCRIPTION
**Pull request by roncain**

### CODE REVIEW

**Comment by roncain** [comment]
@StephenBonikowsky -- I haven't done an exhaustive search but found this trying to experiment adding a src.builds file.

**Comment by roncain** [comment]
#704 will fix this from the TFS side.  Will cancel this PR when that happens.

**Comment by roncain** [comment]
#704 merged so this became redundant.  Closing it.

**Comment by StephenBonikowsky** [comment]
@weshaggard caught and fixed this in TFS.
This went in with the PR that we merged when Jenkins was down otherwise it would have been caught :cry:

**Pull request closed without merging**
