### PR TITLE
Were not bin placing tests in Linux folder when building for Linux.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**

### CODE REVIEW

**Comment by mconnew** [comment]
Can you add an xml comment briefly explaining that this is used to override the OSGroup when creating official builds.

**Comment by StephenBonikowsky** [comment]
Sure, I'll wait until CI passes...hopefully and then amend it with the comment and merge.

**Comment by StephenBonikowsky** [comment]
I should also point out that I tested this in VSTS and confirmed that it fixed the problem.

**Comment by mconnew** [comment]
LGTM functionally.

**Pull request merged**
