### PR TITLE
Add .NET 6.0 TFM to packages

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes https://github.com/dotnet/wcf/issues/4237

See https://github.com/dotnet/designs/pull/222#issuecomment-861617052 for context.

@mconnew I verified these packages restore using the `net6.0` assets in the HelloAndroid sample from https://github.com/dotnet/maui-samples and at least a basic call to a SOAP webservice works.

### CODE REVIEW

**Comment by mconnew** [comment]
@ericstj, can you comment on whether we need to add net6.0 to the Ref projects too? This work is to make the latest Xamarin platform which is based on .NET 6.0 (as opposed to mono) to use the WCF runtime assets from our packages instead of the previous Xamarin in-box mono based implementation.

**Comment by akoeplinger** [comment]
Yes we do need them in the Ref projects too since the packages contain `ref/MonoAndroid10/_._` right now as well, so we need the same explicit net6.0 asset as for `lib`.

**Comment by akoeplinger** [comment]
@mconnew this should be good to go now, Eric gave his thumbs up :)

**Comment by ericstj** [comment]
Yes, to state explicitly: please make parallel changes to TFM additions in ref/src.  You need both here.

**Review by mconnew — APPROVED** [review]

**Pull request merged**
