### PR TITLE
Fill in table of supported RC1 features

### LINKED ISSUE #493: Create Markdown table of feature list for what is supported in OSS
For purposes of putting it on GitHub.

### PR DESCRIPTION
**Pull request by roncain**
First pass at specifying the features available in RC1.

Fixes #493

### CODE REVIEW

**Comment by roncain** [comment]
@StephenBonikowsky @zhenlan @iamjasonp @mconnew @hongdai -- your comments are encouraged asap.  We need to close on the shape and content of this table by Friday (11/20) mid-day at the latest so that I can link to this table from our release notes before I leave for a week.

I know there will be controversy at the layout of the rows (ex: broken down by feature area rather than scenario description) just like our discussions about how to organize scenario tests.  I chose to optimize for existing WCF users being able to recognize which features work at a glance.

Features marked with "?" require further investigation (by me or anyone else) to answer.  At this point, I'd like comments mainly on the structure so I can merge it.  Then anyone else can modify the table emojis and hyperlinks after that to improve its accuracy.

**Comment by roncain** [comment]
Incidentally, this table was edited using https://jbt.github.io/markdown-editor .  I recommend anyone else editing this table use a GitHub flavored editor like that

**Comment by StephenBonikowsky** [comment]
This is a different approach than trying to describe our scenarios but it may actually be the simplest and clearest way to communicate what we support.
Knowing that this is something we can keep discussing and tweaking as needed I'm inclined to say we merge it and continue to work on it over time, we can get feedback from the community as well.

LGTM

**Comment by zhenlan** [comment]
We can tweak some of the details but I really like this!

**Pull request merged**
