### PR TITLE
Numerous changes to scenario tests per Issue #62

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
This includes test class renames.
Test method renames.
Renaming one file.
Moved a couple types out of common code to the same location as the tests that need them.
Updated several tests that were using abstracted helper methods located in common code to just do what they need to do right in the test itself. These types of helper methods make more sense for unit tests than scenario tests, the abstraction is not worth a few extra lines of code.
This pull request fixes Issue #62

### CODE REVIEW

**Comment by SajayAntony** [comment]
This breaks the history for the updated file and I would push back but since the contents are pretty small it might be ok this time. 
:shipit:

**Comment by StephenBonikowsky** [comment]
I used "git mv" to rename it but after editing the contents of the newly moved file it turned into a delete and add. Maybe it needs to be modified first and then moved?

**Comment by SajayAntony** [comment]
Lets just break up the commit next time.

**Comment by iamjasonp** [comment]
There's no great way to move files from what I've found - git basically tracks each move as a delete/add, and "knows" when a file looks similar enough to call it a move.

**Pull request merged**
